#!/usr/bin/env bash
x=$1



DESKTOP_DIR=$(xdg-user-dir DESKTOP)
echo $DESKTOP_DIR

A="install"
B="uninstall"
# path=$(dirname "$0")
path=$(pwd)

if [ "$(id -u)" -eq "0" ]; then
   echo "This script mustn't be run as root" 1>&2
   exit 1
fi

if [ -z ${x} ]
then
  echo You must specify an argument install or uninstall.
elif [ $1 = "install" ]
then
  echo Installing dependencies
  echo "" > files.txt
  echo Installing Learnblock
  gksudo pip install paramiko gitpython
  gksudo python setup.py install
  # gksudo pip install paramiko gitpython && python setup.py install --record files.txt
  cat files.txt
  echo Completed install successfully
  
  echo [Desktop Entry] >> $path/Learnblock.desktop
  echoVersion=1.0 >> $path/Learnblock.desktop
  echoType=Application >> $path/Learnblock.desktop
  echoName=Learnblock >> $path/Learnblock.desktop
  echoComment= >> $path/Learnblock.desktop
  echoExec=python main.py >> $path/Learnblock.desktop
  echoIcon=$path/learnbot_dsl/learnbotCode/ico.png >> $path/Learnblock.desktop
  echoPath=$path/learnbot_dsl/learnbotCode >> $path/Learnblock.desktop
  echoTerminal=false >> $path/Learnblock.desktop
  echoStartupNotify=false >> $path/Learnblock.desktop

  echo [Desktop Entry] >> $DESKTOP_DIR/Learnblock.desktop
  echoVersion=1.0 >> $DESKTOP_DIR/Learnblock.desktop
  echoType=Application >> $DESKTOP_DIR/Learnblock.desktop
  echoName=Learnblock >> $DESKTOP_DIR/Learnblock.desktop
  echoComment= >> $DESKTOP_DIR/Learnblock.desktop
  echoExec=python main.py >> $DESKTOP_DIR/Learnblock.desktop
  echoIcon=$path/learnbot_dsl/learnbotCode/ico.png >> $DESKTOP_DIR/Learnblock.desktop
  echoPath=$path/learnbot_dsl/learnbotCode >> $DESKTOP_DIR/Learnblock.desktop
  echoTerminal=false >> $DESKTOP_DIR/Learnblock.desktop
  echoStartupNotify=false >> $DESKTOP_DIR/Learnblock.desktop

  chmod +x startLearnblock.sh
elif [ $1 = "uninstall" ]
then
  echo Unnstalling Learnblock
  gksu cat files.txt | xargs rm -rf
  gksu rm files.txt
  echo Completed uninstall successfully
else
  echo You must specify an argument install or uninstall.
fi
