#!/usr/bin/env bash
x=$1

A="install"
B="uninstall"
path=`pwd`

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

if [ -z ${x} ]
then
  echo You must specify an argument install or uninstall.
elif [ $1 = "install" ]
then
  pip install paramiko
  python setup.py install --record files.txt
  cat files.txt
  echo Completed install successfully
  echo [Desktop Entry]$'\n'Version=1.0$'\n'Type=Application$'\n'Name=Learnblock$'\n'Comment=$'\n'Exec=$path/startLearnblock.sh$'\n'Icon=$path/learnbot_dsl/learnbotCode/ico.png$'\n'Path=$path$'\n'Terminal=false$'\n'StartupNotify=false > ~/Escritorio/Learnblock.desktop
  echo [Desktop Entry]$'\n'Version=1.0$'\n'Type=Application$'\n'Name=Learnblock$'\n'Comment=$'\n'Exec=$path/startLearnblock.sh$'\n'Icon=$path/learnbot_dsl/learnbotCode/ico.png$'\n'Path=$path$'\n'Terminal=false$'\n'StartupNotify=false > $path/Learnblock.desktop
  chmod +x $path/startLearnblock.sh
elif [ $1 = "uninstall" ]
then
  cat files.txt | xargs rm -rf
  echo Completed uninstall successfully
else
  echo You must specify an argument install or uninstall.
fi
