#!/usr/bin/env bash
x=$1



DESKTOP_DIR=$(xdg-user-dir DESKTOP)
echo $DESKTOP_DIR

A="install"
B="uninstall"
# path=$(dirname "$0")
path=$(pwd)

if [ "$(id -u)" -eq "0" ]; then
   echo "This script mustn't be run as root" 1>&2
   exit 1
fi

if [ -z ${x} ]
then
  echo You must specify an argument install or uninstall.
elif [ $1 = "install" ]
then
  echo Installing dependencies
  echo "" > files.txt
  echo Installing Learnblock
  gksudo pip install paramiko gitpython
  gksudo python setup.py install
  cat files.txt
  echo Completed install successfully

  echo [Desktop Entry] >> $path/Learnblock.desktop
  echo Version=1.0 >> $path/Learnblock.desktop
  echo Type=Application >> $path/Learnblock.desktop
  echo Name=Learnblock >> $path/Learnblock.desktop
  echo Comment= >> $path/Learnblock.desktop
  echo Exec=python main.py >> $path/Learnblock.desktop
  echo Icon=$path/learnbot_dsl/learnbotCode/ico.png >> $path/Learnblock.desktop
  echo Path=$path/learnbot_dsl/learnbotCode >> $path/Learnblock.desktop
  echo Terminal=false >> $path/Learnblock.desktop
  echo StartupNotify=false >> $path/Learnblock.desktop

  echo [Desktop Entry] >> $DESKTOP_DIR/Learnblock.desktop
  echo Version=1.0 >> $DESKTOP_DIR/Learnblock.desktop
  echo Type=Application >> $DESKTOP_DIR/Learnblock.desktop
  echo Name=Learnblock >> $DESKTOP_DIR/Learnblock.desktop
  echo Comment= >> $DESKTOP_DIR/Learnblock.desktop
  echo Exec=python main.py >> $DESKTOP_DIR/Learnblock.desktop
  echo Icon=$path/learnbot_dsl/learnbotCode/ico.png >> $DESKTOP_DIR/Learnblock.desktop
  echo Path=$path/learnbot_dsl/learnbotCode >> $DESKTOP_DIR/Learnblock.desktop
  echo Terminal=false >> $DESKTOP_DIR/Learnblock.desktop
  echo StartupNotify=false >> $DESKTOP_DIR/Learnblock.desktop

  chmod +x startLearnblock.sh
elif [ $1 = "uninstall" ]
then
  echo Unnstalling Learnblock
  gksu cat files.txt | xargs rm -rf
  gksu rm files.txt
  echo Completed uninstall successfully
else
  echo You must specify an argument install or uninstall.
fi
