# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/prinshu/robocomp/components/learnbot/learnbot_dsl/learnbotCode/guis/interface.ui'
#
# Created: Wed Jul  4 10:40:40 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(916, 352)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.AddRobot = QtGui.QPushButton(self.centralwidget)
        self.AddRobot.setObjectName("AddRobot")
        self.verticalLayout_14.addWidget(self.AddRobot)
        self.verticalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.collaborativeTabs = QtGui.QTabWidget(self.centralwidget)
        self.collaborativeTabs.setAutoFillBackground(True)
        self.collaborativeTabs.setObjectName("collaborativeTabs")
        self.verticalLayout_15.addWidget(self.collaborativeTabs)
        self.verticalLayout_4.addLayout(self.verticalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools_robot = QtGui.QMenu(self.menubar)
        self.menuTools_robot.setObjectName("menuTools_robot")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHola = QtGui.QAction(MainWindow)
        self.actionHola.setObjectName("actionHola")
        self.actionCreate_New_block = QtGui.QAction(MainWindow)
        self.actionCreate_New_block.setObjectName("actionCreate_New_block")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_Proyect = QtGui.QAction(MainWindow)
        self.actionOpen_Proyect.setObjectName("actionOpen_Proyect")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionStart_simulator = QtGui.QAction(MainWindow)
        self.actionStart_simulator.setObjectName("actionStart_simulator")
        self.actionStart_components = QtGui.QAction(MainWindow)
        self.actionStart_components.setObjectName("actionStart_components")
        self.actionReboot = QtGui.QAction(MainWindow)
        self.actionReboot.setObjectName("actionReboot")
        self.actionShutdown = QtGui.QAction(MainWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.menuFile.addAction(self.actionCreate_New_block)
        self.menuFile.addAction(self.actionOpen_Proyect)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools_robot.addAction(self.actionStart_simulator)
        self.menuTools_robot.addAction(self.actionStart_components)
        self.menuTools_robot.addAction(self.actionReboot)
        self.menuTools_robot.addAction(self.actionShutdown)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools_robot.menuAction())

        self.retranslateUi(MainWindow)
        self.collaborativeTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.AddRobot.setText(QtGui.QApplication.translate("MainWindow", "AddRobot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools_robot.setTitle(QtGui.QApplication.translate("MainWindow", "tools robot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHola.setText(QtGui.QApplication.translate("MainWindow", "Añadir Nueva Metodo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_New_block.setText(QtGui.QApplication.translate("MainWindow", "Create New block", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save Proyect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Proyect.setText(QtGui.QApplication.translate("MainWindow", "Open Proyect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_simulator.setText(QtGui.QApplication.translate("MainWindow", "Start Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_components.setText(QtGui.QApplication.translate("MainWindow", "Start components", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReboot.setText(QtGui.QApplication.translate("MainWindow", "Reboot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShutdown.setText(QtGui.QApplication.translate("MainWindow", "Shutdown", None, QtGui.QApplication.UnicodeUTF8))

