# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/prinshu/robocomp/components/learnbot/learnbot_dsl/learnbotCode/guis/setConfiguration.ui'
#
# Created: Wed Jul  4 10:40:40 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(546, 752)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Default = QtGui.QPushButton(Dialog)
        self.Default.setObjectName("Default")
        self.verticalLayout.addWidget(self.Default)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.IPAdress = QtGui.QLabel(Dialog)
        self.IPAdress.setObjectName("IPAdress")
        self.horizontalLayout_2.addWidget(self.IPAdress)
        self.IP = QtGui.QLineEdit(Dialog)
        self.IP.setObjectName("IP")
        self.horizontalLayout_2.addWidget(self.IP)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.userName = QtGui.QLabel(Dialog)
        self.userName.setObjectName("userName")
        self.horizontalLayout_3.addWidget(self.userName)
        self.user = QtGui.QLineEdit(Dialog)
        self.user.setObjectName("user")
        self.horizontalLayout_3.addWidget(self.user)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PasswordLabel = QtGui.QLabel(Dialog)
        self.PasswordLabel.setTextFormat(QtCore.Qt.AutoText)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.horizontalLayout_4.addWidget(self.PasswordLabel)
        self.password = QtGui.QLineEdit(Dialog)
        self.password.setObjectName("password")
        self.horizontalLayout_4.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.commandStart = QtGui.QLabel(Dialog)
        self.commandStart.setObjectName("commandStart")
        self.horizontalLayout_5.addWidget(self.commandStart)
        self.start = QtGui.QLineEdit(Dialog)
        self.start.setObjectName("start")
        self.horizontalLayout_5.addWidget(self.start)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.stop = QtGui.QLineEdit(Dialog)
        self.stop.setObjectName("stop")
        self.horizontalLayout_6.addWidget(self.stop)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.startSimulator = QtGui.QLineEdit(Dialog)
        self.startSimulator.setObjectName("startSimulator")
        self.horizontalLayout_7.addWidget(self.startSimulator)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.PortDiff = QtGui.QLineEdit(Dialog)
        self.PortDiff.setObjectName("PortDiff")
        self.horizontalLayout_9.addWidget(self.PortDiff)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.PortLaser = QtGui.QLineEdit(Dialog)
        self.PortLaser.setObjectName("PortLaser")
        self.horizontalLayout_10.addWidget(self.PortLaser)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.PortEmotion = QtGui.QLineEdit(Dialog)
        self.PortEmotion.setObjectName("PortEmotion")
        self.horizontalLayout_12.addWidget(self.PortEmotion)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.PortJoint = QtGui.QLineEdit(Dialog)
        self.PortJoint.setObjectName("PortJoint")
        self.horizontalLayout_13.addWidget(self.PortJoint)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.Laser1 = QtGui.QLineEdit(Dialog)
        self.Laser1.setObjectName("Laser1")
        self.horizontalLayout_14.addWidget(self.Laser1)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10)
        self.Laser2 = QtGui.QLineEdit(Dialog)
        self.Laser2.setObjectName("Laser2")
        self.horizontalLayout_15.addWidget(self.Laser2)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.Laser3 = QtGui.QLineEdit(Dialog)
        self.Laser3.setObjectName("Laser3")
        self.horizontalLayout_16.addWidget(self.Laser3)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.Laser4 = QtGui.QLineEdit(Dialog)
        self.Laser4.setObjectName("Laser4")
        self.horizontalLayout_17.addWidget(self.Laser4)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_18.addWidget(self.label_13)
        self.Laser5 = QtGui.QLineEdit(Dialog)
        self.Laser5.setObjectName("Laser5")
        self.horizontalLayout_18.addWidget(self.Laser5)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.Laser6 = QtGui.QLineEdit(Dialog)
        self.Laser6.setObjectName("Laser6")
        self.horizontalLayout_19.addWidget(self.Laser6)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        self.Laser7 = QtGui.QLineEdit(Dialog)
        self.Laser7.setObjectName("Laser7")
        self.horizontalLayout_20.addWidget(self.Laser7)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_21.addWidget(self.label_16)
        self.RGBD = QtGui.QLineEdit(Dialog)
        self.RGBD.setObjectName("RGBD")
        self.horizontalLayout_21.addWidget(self.RGBD)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.display = QtGui.QLineEdit(Dialog)
        self.display.setObjectName("display")
        self.horizontalLayout_22.addWidget(self.display)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelPushButton = QtGui.QPushButton(Dialog)
        self.cancelPushButton.setAutoDefault(False)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.okPushButton = QtGui.QPushButton(Dialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.Default.setText(QtGui.QApplication.translate("Dialog", "Use Default", None, QtGui.QApplication.UnicodeUTF8))
        self.IPAdress.setText(QtGui.QApplication.translate("Dialog", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.userName.setText(QtGui.QApplication.translate("Dialog", "Username ", None, QtGui.QApplication.UnicodeUTF8))
        self.PasswordLabel.setText(QtGui.QApplication.translate("Dialog", "Password  ", None, QtGui.QApplication.UnicodeUTF8))
        self.commandStart.setText(QtGui.QApplication.translate("Dialog", "command_start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "command_stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "command_start_simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Port_DifferentialRobotProxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Port_LaserProxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Port_EmotionMotorProxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Port_JointMotorProxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Port_Laser1Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Port_Laser2Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Port_Laser3Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Port_Laser4Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Port_Laser5Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Port_Laser6Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Port_Laser7Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Port_RGBDProxy ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Port_DisplayProxy", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.okPushButton.setText(QtGui.QApplication.translate("Dialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))

