# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/prinshu/robocomp/components/learnbot/learnbot_dsl/learnbotCode/guis/tab.ui'
#
# Created: Wed Jul  4 10:40:40 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Tabs(object):
    def setupUi(self, Tabs):
        Tabs.setObjectName("Tabs")
        Tabs.resize(884, 826)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Tabs)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.openpushButton = QtGui.QPushButton(Tabs)
        self.openpushButton.setText("")
        self.openpushButton.setObjectName("openpushButton")
        self.horizontalLayout_7.addWidget(self.openpushButton)
        self.savepushButton = QtGui.QPushButton(Tabs)
        self.savepushButton.setText("")
        self.savepushButton.setObjectName("savepushButton")
        self.horizontalLayout_7.addWidget(self.savepushButton)
        self.zoompushButton = QtGui.QPushButton(Tabs)
        self.zoompushButton.setText("")
        self.zoompushButton.setCheckable(True)
        self.zoompushButton.setObjectName("zoompushButton")
        self.horizontalLayout_7.addWidget(self.zoompushButton)
        self.addNumberpushButton = QtGui.QPushButton(Tabs)
        self.addNumberpushButton.setObjectName("addNumberpushButton")
        self.horizontalLayout_7.addWidget(self.addNumberpushButton)
        self.addStringpushButton = QtGui.QPushButton(Tabs)
        self.addStringpushButton.setObjectName("addStringpushButton")
        self.horizontalLayout_7.addWidget(self.addStringpushButton)
        self.useEventscheckBox = QtGui.QCheckBox(Tabs)
        self.useEventscheckBox.setObjectName("useEventscheckBox")
        self.horizontalLayout_7.addWidget(self.useEventscheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.language = QtGui.QComboBox(Tabs)
        self.language.setMaximumSize(QtCore.QSize(85, 27))
        self.language.setObjectName("language")
        self.language.addItem("")
        self.language.addItem("")
        self.horizontalLayout_7.addWidget(self.language)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.Tabwi = QtGui.QTabWidget(Tabs)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tabwi.setFont(font)
        self.Tabwi.setTabPosition(QtGui.QTabWidget.North)
        self.Tabwi.setTabShape(QtGui.QTabWidget.Rounded)
        self.Tabwi.setObjectName("Tabwi")
        self.program_text = QtGui.QWidget()
        self.program_text.setEnabled(False)
        self.program_text.setObjectName("program_text")
        self.horizontalLayout = QtGui.QHBoxLayout(self.program_text)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtGui.QLabel(self.program_text)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.textCode = QtGui.QPlainTextEdit(self.program_text)
        self.textCode.setObjectName("textCode")
        self.verticalLayout_6.addWidget(self.textCode)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.camera = QtGui.QFrame(self.program_text)
        self.camera.setMinimumSize(QtCore.QSize(320, 240))
        self.camera.setMaximumSize(QtCore.QSize(320, 240))
        self.camera.setFrameShape(QtGui.QFrame.StyledPanel)
        self.camera.setFrameShadow(QtGui.QFrame.Raised)
        self.camera.setObjectName("camera")
        self.verticalLayout_5.addWidget(self.camera)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.startTextPushButton = QtGui.QPushButton(self.program_text)
        self.startTextPushButton.setEnabled(False)
        self.startTextPushButton.setObjectName("startTextPushButton")
        self.horizontalLayout_5.addWidget(self.startTextPushButton)
        self.stoptextPushButton = QtGui.QPushButton(self.program_text)
        self.stoptextPushButton.setEnabled(False)
        self.stoptextPushButton.setObjectName("stoptextPushButton")
        self.horizontalLayout_5.addWidget(self.stoptextPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.Tabwi.addTab(self.program_text, "")
        self.program_visual = QtGui.QWidget()
        self.program_visual.setObjectName("program_visual")
        self.gridLayout = QtGui.QGridLayout(self.program_visual)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.program_visual)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.functions = QtGui.QTabWidget(self.splitter)
        self.functions.setEnabled(True)
        self.functions.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.functions.setFont(font)
        self.functions.setTabPosition(QtGui.QTabWidget.West)
        self.functions.setObjectName("functions")
        self.search = QtGui.QWidget()
        self.search.setObjectName("search")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.search)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.SearchlineEdit = QtGui.QLineEdit(self.search)
        self.SearchlineEdit.setObjectName("SearchlineEdit")
        self.verticalLayout_16.addWidget(self.SearchlineEdit)
        self.tableSearch = QtGui.QTableWidget(self.search)
        self.tableSearch.setShowGrid(False)
        self.tableSearch.setGridStyle(QtCore.Qt.NoPen)
        self.tableSearch.setObjectName("tableSearch")
        self.tableSearch.setColumnCount(0)
        self.tableSearch.setRowCount(0)
        self.tableSearch.horizontalHeader().setVisible(False)
        self.tableSearch.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tableSearch)
        self.functions.addTab(self.search, "")
        self.control = QtGui.QWidget()
        self.control.setObjectName("control")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.control)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.addWhenpushButton = QtGui.QPushButton(self.control)
        self.addWhenpushButton.setObjectName("addWhenpushButton")
        self.verticalLayout_12.addWidget(self.addWhenpushButton)
        self.deleteWhenpushButton = QtGui.QPushButton(self.control)
        self.deleteWhenpushButton.setEnabled(False)
        self.deleteWhenpushButton.setObjectName("deleteWhenpushButton")
        self.verticalLayout_12.addWidget(self.deleteWhenpushButton)
        self.tableControl = QtGui.QTableWidget(self.control)
        self.tableControl.setShowGrid(False)
        self.tableControl.setGridStyle(QtCore.Qt.NoPen)
        self.tableControl.setObjectName("tableControl")
        self.tableControl.setColumnCount(0)
        self.tableControl.setRowCount(0)
        self.verticalLayout_12.addWidget(self.tableControl)
        self.functions.addTab(self.control, "")
        self.express = QtGui.QWidget()
        self.express.setObjectName("express")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.express)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tableExpress = QtGui.QTableWidget(self.express)
        self.tableExpress.setShowGrid(False)
        self.tableExpress.setGridStyle(QtCore.Qt.NoPen)
        self.tableExpress.setObjectName("tableExpress")
        self.tableExpress.setColumnCount(0)
        self.tableExpress.setRowCount(0)
        self.verticalLayout_14.addWidget(self.tableExpress)
        self.functions.addTab(self.express, "")
        self.move = QtGui.QWidget()
        self.move.setObjectName("move")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.move)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tableMotor = QtGui.QTableWidget(self.move)
        self.tableMotor.setShowGrid(False)
        self.tableMotor.setGridStyle(QtCore.Qt.NoPen)
        self.tableMotor.setObjectName("tableMotor")
        self.tableMotor.setColumnCount(0)
        self.tableMotor.setRowCount(0)
        self.verticalLayout_11.addWidget(self.tableMotor)
        self.functions.addTab(self.move, "")
        self.sensors = QtGui.QWidget()
        self.sensors.setObjectName("sensors")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.sensors)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tablePerceptual = QtGui.QTableWidget(self.sensors)
        self.tablePerceptual.setShowGrid(False)
        self.tablePerceptual.setGridStyle(QtCore.Qt.NoPen)
        self.tablePerceptual.setObjectName("tablePerceptual")
        self.tablePerceptual.setColumnCount(0)
        self.tablePerceptual.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tablePerceptual)
        self.functions.addTab(self.sensors, "")
        self.propioperceptive = QtGui.QWidget()
        self.propioperceptive.setObjectName("propioperceptive")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.propioperceptive)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tablePropioperceptive = QtGui.QTableWidget(self.propioperceptive)
        self.tablePropioperceptive.setShowGrid(False)
        self.tablePropioperceptive.setGridStyle(QtCore.Qt.NoPen)
        self.tablePropioperceptive.setObjectName("tablePropioperceptive")
        self.tablePropioperceptive.setColumnCount(0)
        self.tablePropioperceptive.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tablePropioperceptive)
        self.functions.addTab(self.propioperceptive, "")
        self.collab = QtGui.QWidget()
        self.collab.setEnabled(True)
        self.collab.setObjectName("collab")
        self.tableCollab = QtGui.QTableWidget(self.collab)
        self.tableCollab.setGeometry(QtCore.QRect(9, 9, 131, 701))
        self.tableCollab.setShowGrid(False)
        self.tableCollab.setGridStyle(QtCore.Qt.NoPen)
        self.tableCollab.setObjectName("tableCollab")
        self.tableCollab.setColumnCount(0)
        self.tableCollab.setRowCount(0)
        self.functions.addTab(self.collab, "")
        self.operators = QtGui.QWidget()
        self.operators.setObjectName("operators")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.operators)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableOperadores = QtGui.QTableWidget(self.operators)
        self.tableOperadores.setShowGrid(False)
        self.tableOperadores.setGridStyle(QtCore.Qt.NoPen)
        self.tableOperadores.setObjectName("tableOperadores")
        self.tableOperadores.setColumnCount(0)
        self.tableOperadores.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableOperadores)
        self.functions.addTab(self.operators, "")
        self.variables = QtGui.QWidget()
        self.variables.setEnabled(True)
        self.variables.setObjectName("variables")
        self.verticalLayout = QtGui.QVBoxLayout(self.variables)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addVarPushButton = QtGui.QPushButton(self.variables)
        self.addVarPushButton.setEnabled(True)
        self.addVarPushButton.setObjectName("addVarPushButton")
        self.verticalLayout_2.addWidget(self.addVarPushButton)
        self.deleteVarPushButton = QtGui.QPushButton(self.variables)
        self.deleteVarPushButton.setEnabled(False)
        self.deleteVarPushButton.setObjectName("deleteVarPushButton")
        self.verticalLayout_2.addWidget(self.deleteVarPushButton)
        self.pushButton_6 = QtGui.QPushButton(self.variables)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tableVariables = QtGui.QTableWidget(self.variables)
        self.tableVariables.setShowGrid(False)
        self.tableVariables.setGridStyle(QtCore.Qt.NoPen)
        self.tableVariables.setObjectName("tableVariables")
        self.tableVariables.setColumnCount(0)
        self.tableVariables.setRowCount(0)
        self.verticalLayout.addWidget(self.tableVariables)
        self.functions.addTab(self.variables, "")
        self.user_funtions = QtGui.QWidget()
        self.user_funtions.setObjectName("user_funtions")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.user_funtions)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.createFunctionsPushButton = QtGui.QPushButton(self.user_funtions)
        self.createFunctionsPushButton.setEnabled(True)
        self.createFunctionsPushButton.setObjectName("createFunctionsPushButton")
        self.verticalLayout_8.addWidget(self.createFunctionsPushButton)
        self.deleteFuntionsPushButton = QtGui.QPushButton(self.user_funtions)
        self.deleteFuntionsPushButton.setEnabled(False)
        self.deleteFuntionsPushButton.setObjectName("deleteFuntionsPushButton")
        self.verticalLayout_8.addWidget(self.deleteFuntionsPushButton)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        self.tableUserfunctions = QtGui.QTableWidget(self.user_funtions)
        self.tableUserfunctions.setShowGrid(False)
        self.tableUserfunctions.setGridStyle(QtCore.Qt.NoPen)
        self.tableUserfunctions.setObjectName("tableUserfunctions")
        self.tableUserfunctions.setColumnCount(0)
        self.tableUserfunctions.setRowCount(0)
        self.verticalLayout_13.addWidget(self.tableUserfunctions)
        self.functions.addTab(self.user_funtions, "")
        self.others = QtGui.QWidget()
        self.others.setObjectName("others")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.others)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableOthers = QtGui.QTableWidget(self.others)
        self.tableOthers.setShowGrid(False)
        self.tableOthers.setGridStyle(QtCore.Qt.NoPen)
        self.tableOthers.setObjectName("tableOthers")
        self.tableOthers.setColumnCount(0)
        self.tableOthers.setRowCount(0)
        self.verticalLayout_15.addWidget(self.tableOthers)
        self.functions.addTab(self.others, "")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startPushButton = QtGui.QPushButton(self.layoutWidget)
        self.startPushButton.setMaximumSize(QtCore.QSize(16777215, 27))
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout_4.addWidget(self.startPushButton)
        self.startPRPushButton = QtGui.QPushButton(self.layoutWidget)
        self.startPRPushButton.setObjectName("startPRPushButton")
        self.horizontalLayout_4.addWidget(self.startPRPushButton)
        self.startCollaborative = QtGui.QPushButton(self.layoutWidget)
        self.startCollaborative.setObjectName("startCollaborative")
        self.horizontalLayout_4.addWidget(self.startCollaborative)
        self.setConfig = QtGui.QPushButton(self.layoutWidget)
        self.setConfig.setObjectName("setConfig")
        self.horizontalLayout_4.addWidget(self.setConfig)
        self.stopPushButton = QtGui.QPushButton(self.layoutWidget)
        self.stopPushButton.setMaximumSize(QtCore.QSize(16777215, 27))
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_4.addWidget(self.stopPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.Tabwi.addTab(self.program_visual, "")
        self.verticalLayout_4.addWidget(self.Tabwi)

        self.retranslateUi(Tabs)
        self.Tabwi.setCurrentIndex(1)
        self.functions.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Tabs)

    def retranslateUi(self, Tabs):
        Tabs.setWindowTitle(QtGui.QApplication.translate("Tabs", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.openpushButton.setToolTip(QtGui.QApplication.translate("Tabs", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.savepushButton.setToolTip(QtGui.QApplication.translate("Tabs", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.zoompushButton.setToolTip(QtGui.QApplication.translate("Tabs", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.addNumberpushButton.setToolTip(QtGui.QApplication.translate("Tabs", "Add Number", None, QtGui.QApplication.UnicodeUTF8))
        self.addNumberpushButton.setText(QtGui.QApplication.translate("Tabs", "Add Number", None, QtGui.QApplication.UnicodeUTF8))
        self.addStringpushButton.setToolTip(QtGui.QApplication.translate("Tabs", "Add String", None, QtGui.QApplication.UnicodeUTF8))
        self.addStringpushButton.setText(QtGui.QApplication.translate("Tabs", "Add String", None, QtGui.QApplication.UnicodeUTF8))
        self.useEventscheckBox.setText(QtGui.QApplication.translate("Tabs", "Use Events", None, QtGui.QApplication.UnicodeUTF8))
        self.language.setItemText(0, QtGui.QApplication.translate("Tabs", "ES", None, QtGui.QApplication.UnicodeUTF8))
        self.language.setItemText(1, QtGui.QApplication.translate("Tabs", "EN", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabwi.setWhatsThis(QtGui.QApplication.translate("Tabs", "<html><head/><body><p>H</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Tabs", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.startTextPushButton.setText(QtGui.QApplication.translate("Tabs", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stoptextPushButton.setText(QtGui.QApplication.translate("Tabs", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.program_text), QtGui.QApplication.translate("Tabs", "Text Code", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.search), QtGui.QApplication.translate("Tabs", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.addWhenpushButton.setText(QtGui.QApplication.translate("Tabs", "Add When", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteWhenpushButton.setText(QtGui.QApplication.translate("Tabs", "Delete When", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.control), QtGui.QApplication.translate("Tabs", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.express), QtGui.QApplication.translate("Tabs", "Expressions", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.move), QtGui.QApplication.translate("Tabs", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.sensors), QtGui.QApplication.translate("Tabs", "Perceptual", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.propioperceptive), QtGui.QApplication.translate("Tabs", "Proprioceptive", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.collab), QtGui.QApplication.translate("Tabs", "collaborative", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.operators), QtGui.QApplication.translate("Tabs", "Operators", None, QtGui.QApplication.UnicodeUTF8))
        self.addVarPushButton.setText(QtGui.QApplication.translate("Tabs", "Add Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteVarPushButton.setText(QtGui.QApplication.translate("Tabs", "Delete Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("Tabs", "Add List", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.variables), QtGui.QApplication.translate("Tabs", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.createFunctionsPushButton.setText(QtGui.QApplication.translate("Tabs", "Create Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteFuntionsPushButton.setText(QtGui.QApplication.translate("Tabs", "Delete Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.user_funtions), QtGui.QApplication.translate("Tabs", "User functions", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.others), QtGui.QApplication.translate("Tabs", "Others", None, QtGui.QApplication.UnicodeUTF8))
        self.startPushButton.setText(QtGui.QApplication.translate("Tabs", "Start (simulated robot)", None, QtGui.QApplication.UnicodeUTF8))
        self.startPRPushButton.setText(QtGui.QApplication.translate("Tabs", "Start (physical robot)", None, QtGui.QApplication.UnicodeUTF8))
        self.startCollaborative.setText(QtGui.QApplication.translate("Tabs", "Start(Collaborative)", None, QtGui.QApplication.UnicodeUTF8))
        self.setConfig.setText(QtGui.QApplication.translate("Tabs", "setConfiguration", None, QtGui.QApplication.UnicodeUTF8))
        self.stopPushButton.setText(QtGui.QApplication.translate("Tabs", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.program_visual), QtGui.QApplication.translate("Tabs", "LearnBlock", None, QtGui.QApplication.UnicodeUTF8))

