//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: tts.ice
//  Source: tts.idsl
//  
//****************************************************************** 
#ifndef ROBOCOMPTTSPEECH_ICE
#define ROBOCOMPTTSPEECH_ICE
module RoboCompTTSpeech
{
	interface TTSpeech
	{
		void say (string text);
		void sayLanguage (string text, string language);
		void sayVoice (string text, int voz);
	};
};

#endif
