# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateBlock.ui',
# licensing of 'CreateBlock.ui' applies.
#
# Created: Sun Sep  8 19:09:48 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(867, 779)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(102, 27))
        self.label_4.setMaximumSize(QtCore.QSize(130, 27))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.lineEditName = QtWidgets.QLineEdit(Dialog)
        self.lineEditName.setMinimumSize(QtCore.QSize(331, 27))
        self.lineEditName.setMaximumSize(QtCore.QSize(331, 27))
        self.lineEditName.setToolTip("")
        self.lineEditName.setObjectName("lineEditName")
        self.horizontalLayout_10.addWidget(self.lineEditName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_18.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(102, 27))
        self.label_2.setMaximumSize(QtCore.QSize(130, 27))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBoxBlockImage = QtWidgets.QComboBox(Dialog)
        self.comboBoxBlockImage.setMaximumSize(QtCore.QSize(110, 27))
        self.comboBoxBlockImage.setToolTip("")
        self.comboBoxBlockImage.setObjectName("comboBoxBlockImage")
        self.horizontalLayout_3.addWidget(self.comboBoxBlockImage)
        self.pushButtonAddBlockImage = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddBlockImage.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonAddBlockImage.setAutoDefault(False)
        self.pushButtonAddBlockImage.setObjectName("pushButtonAddBlockImage")
        self.horizontalLayout_3.addWidget(self.pushButtonAddBlockImage)
        self.pushButtonRemoveBlockImage = QtWidgets.QPushButton(Dialog)
        self.pushButtonRemoveBlockImage.setEnabled(False)
        self.pushButtonRemoveBlockImage.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRemoveBlockImage.setAutoDefault(False)
        self.pushButtonRemoveBlockImage.setObjectName("pushButtonRemoveBlockImage")
        self.horizontalLayout_3.addWidget(self.pushButtonRemoveBlockImage)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.listWidgetBlockImage = QtWidgets.QListWidget(Dialog)
        self.listWidgetBlockImage.setMaximumSize(QtCore.QSize(16777215, 103))
        self.listWidgetBlockImage.setObjectName("listWidgetBlockImage")
        self.horizontalLayout_4.addWidget(self.listWidgetBlockImage)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem2)
        self.BlockImage = QtWidgets.QLabel(Dialog)
        self.BlockImage.setMinimumSize(QtCore.QSize(161, 111))
        self.BlockImage.setText("")
        self.BlockImage.setObjectName("BlockImage")
        self.verticalLayout_7.addWidget(self.BlockImage)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_18.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(102, 27))
        self.label_6.setMaximumSize(QtCore.QSize(130, 27))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBoxBlockType = QtWidgets.QComboBox(Dialog)
        self.comboBoxBlockType.setMaximumSize(QtCore.QSize(130, 27))
        self.comboBoxBlockType.setObjectName("comboBoxBlockType")
        self.comboBoxBlockType.addItem("")
        self.comboBoxBlockType.addItem("")
        self.comboBoxBlockType.addItem("")
        self.comboBoxBlockType.addItem("")
        self.comboBoxBlockType.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxBlockType)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditCategory = QtWidgets.QLineEdit(Dialog)
        self.lineEditCategory.setObjectName("lineEditCategory")
        self.horizontalLayout.addWidget(self.lineEditCategory)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_18.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(102, 27))
        self.label_5.setMaximumSize(QtCore.QSize(102, 27))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonAddVar = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddVar.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonAddVar.setAutoDefault(False)
        self.pushButtonAddVar.setObjectName("pushButtonAddVar")
        self.horizontalLayout_7.addWidget(self.pushButtonAddVar)
        self.pushButtonRemoveVar = QtWidgets.QPushButton(Dialog)
        self.pushButtonRemoveVar.setEnabled(False)
        self.pushButtonRemoveVar.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRemoveVar.setAutoDefault(False)
        self.pushButtonRemoveVar.setObjectName("pushButtonRemoveVar")
        self.horizontalLayout_7.addWidget(self.pushButtonRemoveVar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.tableWidgetVars = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetVars.setMinimumSize(QtCore.QSize(330, 0))
        self.tableWidgetVars.setMaximumSize(QtCore.QSize(301, 16777215))
        self.tableWidgetVars.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetVars.setAutoScroll(True)
        self.tableWidgetVars.setObjectName("tableWidgetVars")
        self.tableWidgetVars.setColumnCount(3)
        self.tableWidgetVars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVars.setHorizontalHeaderItem(2, item)
        self.tableWidgetVars.horizontalHeader().setVisible(True)
        self.tableWidgetVars.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableWidgetVars)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMinimumSize(QtCore.QSize(102, 27))
        self.label_7.setMaximumSize(QtCore.QSize(102, 27))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonAddlanguages = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddlanguages.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonAddlanguages.setAutoDefault(False)
        self.pushButtonAddlanguages.setObjectName("pushButtonAddlanguages")
        self.horizontalLayout_8.addWidget(self.pushButtonAddlanguages)
        self.pushButtonRemovelanguages = QtWidgets.QPushButton(Dialog)
        self.pushButtonRemovelanguages.setEnabled(False)
        self.pushButtonRemovelanguages.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRemovelanguages.setAutoDefault(False)
        self.pushButtonRemovelanguages.setObjectName("pushButtonRemovelanguages")
        self.horizontalLayout_8.addWidget(self.pushButtonRemovelanguages)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.tableWidgetlanguages = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetlanguages.setMinimumSize(QtCore.QSize(250, 0))
        self.tableWidgetlanguages.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableWidgetlanguages.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetlanguages.setAutoScroll(True)
        self.tableWidgetlanguages.setObjectName("tableWidgetlanguages")
        self.tableWidgetlanguages.setColumnCount(2)
        self.tableWidgetlanguages.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlanguages.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetlanguages.setHorizontalHeaderItem(1, item)
        self.tableWidgetlanguages.horizontalHeader().setVisible(True)
        self.tableWidgetlanguages.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableWidgetlanguages)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_18.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setMinimumSize(QtCore.QSize(102, 27))
        self.label_11.setMaximumSize(QtCore.QSize(102, 27))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_16.addWidget(self.label_11)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem9)
        self.horizontalLayout_16.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButtonAddTooltip = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddTooltip.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonAddTooltip.setAutoDefault(False)
        self.pushButtonAddTooltip.setObjectName("pushButtonAddTooltip")
        self.horizontalLayout_19.addWidget(self.pushButtonAddTooltip)
        self.pushButtonRemoveTooltip = QtWidgets.QPushButton(Dialog)
        self.pushButtonRemoveTooltip.setEnabled(False)
        self.pushButtonRemoveTooltip.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRemoveTooltip.setAutoDefault(False)
        self.pushButtonRemoveTooltip.setObjectName("pushButtonRemoveTooltip")
        self.horizontalLayout_19.addWidget(self.pushButtonRemoveTooltip)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.verticalLayout_17.addLayout(self.horizontalLayout_19)
        self.tableWidgetToolTip = QtWidgets.QTableWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetToolTip.sizePolicy().hasHeightForWidth())
        self.tableWidgetToolTip.setSizePolicy(sizePolicy)
        self.tableWidgetToolTip.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetToolTip.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidgetToolTip.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetToolTip.setAutoScroll(True)
        self.tableWidgetToolTip.setObjectName("tableWidgetToolTip")
        self.tableWidgetToolTip.setColumnCount(2)
        self.tableWidgetToolTip.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetToolTip.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetToolTip.setHorizontalHeaderItem(1, item)
        self.tableWidgetToolTip.horizontalHeader().setVisible(True)
        self.tableWidgetToolTip.verticalHeader().setVisible(False)
        self.verticalLayout_17.addWidget(self.tableWidgetToolTip)
        self.horizontalLayout_16.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButtonConfigFile = QtWidgets.QPushButton(Dialog)
        self.pushButtonConfigFile.setObjectName("pushButtonConfigFile")
        self.horizontalLayout_12.addWidget(self.pushButtonConfigFile)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.lineEditConfigFile = QtWidgets.QLineEdit(Dialog)
        self.lineEditConfigFile.setMinimumSize(QtCore.QSize(650, 0))
        self.lineEditConfigFile.setObjectName("lineEditConfigFile")
        self.horizontalLayout_12.addWidget(self.lineEditConfigFile)
        self.verticalLayout_18.addLayout(self.horizontalLayout_12)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_18.addWidget(self.label)
        self.textEditPythonCode = QtWidgets.QTextEdit(Dialog)
        self.textEditPythonCode.setObjectName("textEditPythonCode")
        self.verticalLayout_18.addWidget(self.textEditPythonCode)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonCancel.setAutoDefault(False)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_9.addWidget(self.pushButtonCancel)
        self.pushButtonOK = QtWidgets.QPushButton(Dialog)
        self.pushButtonOK.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout_9.addWidget(self.pushButtonOK)
        self.verticalLayout_18.addLayout(self.horizontalLayout_9)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButtonOK, self.lineEditName)
        Dialog.setTabOrder(self.lineEditName, self.comboBoxBlockImage)
        Dialog.setTabOrder(self.comboBoxBlockImage, self.pushButtonAddBlockImage)
        Dialog.setTabOrder(self.pushButtonAddBlockImage, self.pushButtonRemoveBlockImage)
        Dialog.setTabOrder(self.pushButtonRemoveBlockImage, self.listWidgetBlockImage)
        Dialog.setTabOrder(self.listWidgetBlockImage, self.comboBoxBlockType)
        Dialog.setTabOrder(self.comboBoxBlockType, self.pushButtonRemoveVar)
        Dialog.setTabOrder(self.pushButtonRemoveVar, self.tableWidgetVars)
        Dialog.setTabOrder(self.tableWidgetVars, self.pushButtonCancel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Create a new block", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Block name:", None, -1))
        self.lineEditName.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Name of the new block", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Block image:", None, -1))
        self.pushButtonAddBlockImage.setText(QtWidgets.QApplication.translate("Dialog", "Add", None, -1))
        self.pushButtonRemoveBlockImage.setText(QtWidgets.QApplication.translate("Dialog", "Remove", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Block type:", None, -1))
        self.comboBoxBlockType.setItemText(0, QtWidgets.QApplication.translate("Dialog", "EXPRESSION", None, -1))
        self.comboBoxBlockType.setItemText(1, QtWidgets.QApplication.translate("Dialog", "MOTOR", None, -1))
        self.comboBoxBlockType.setItemText(2, QtWidgets.QApplication.translate("Dialog", "PERCEPTUAL", None, -1))
        self.comboBoxBlockType.setItemText(3, QtWidgets.QApplication.translate("Dialog", "PROPRIOPERCEPTIVE", None, -1))
        self.comboBoxBlockType.setItemText(4, QtWidgets.QApplication.translate("Dialog", "OTHERS", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Block category:", None, -1))
        self.lineEditCategory.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Category of the new block", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Variables:", None, -1))
        self.pushButtonAddVar.setText(QtWidgets.QApplication.translate("Dialog", "Add", None, -1))
        self.pushButtonRemoveVar.setText(QtWidgets.QApplication.translate("Dialog", "Remove", None, -1))
        self.tableWidgetVars.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Type", None, -1))
        self.tableWidgetVars.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.tableWidgetVars.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Dialog", "Default value", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Languages:", None, -1))
        self.pushButtonAddlanguages.setText(QtWidgets.QApplication.translate("Dialog", "Add", None, -1))
        self.pushButtonRemovelanguages.setText(QtWidgets.QApplication.translate("Dialog", "Remove", None, -1))
        self.tableWidgetlanguages.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Language", None, -1))
        self.tableWidgetlanguages.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "Languages:", None, -1))
        self.pushButtonAddTooltip.setText(QtWidgets.QApplication.translate("Dialog", "Add", None, -1))
        self.pushButtonRemoveTooltip.setText(QtWidgets.QApplication.translate("Dialog", "Remove", None, -1))
        self.tableWidgetToolTip.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Language", None, -1))
        self.tableWidgetToolTip.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Tooltip", None, -1))
        self.pushButtonConfigFile.setText(QtWidgets.QApplication.translate("Dialog", "Select configuration file", None, -1))
        self.lineEditConfigFile.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Complete path of the block configuration file where the new block will be added", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Python Code", None, -1))
        self.pushButtonCancel.setText(QtWidgets.QApplication.translate("Dialog", "CANCEL", None, -1))
        self.pushButtonOK.setText(QtWidgets.QApplication.translate("Dialog", "OK", None, -1))

