# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ivan/robocomp/components/learnbot/learnbot_dsl/guis/Learnblock.ui'
#
# Created: Fri Nov  2 12:11:25 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(955, 790)
        MainWindow.setCursor(QtCore.Qt.ArrowCursor)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openpushButton = QtGui.QPushButton(self.centralwidget)
        self.openpushButton.setText("")
        self.openpushButton.setObjectName("openpushButton")
        self.horizontalLayout_2.addWidget(self.openpushButton)
        self.savepushButton = QtGui.QPushButton(self.centralwidget)
        self.savepushButton.setText("")
        self.savepushButton.setObjectName("savepushButton")
        self.horizontalLayout_2.addWidget(self.savepushButton)
        self.zoompushButton = QtGui.QPushButton(self.centralwidget)
        self.zoompushButton.setText("")
        self.zoompushButton.setCheckable(True)
        self.zoompushButton.setObjectName("zoompushButton")
        self.horizontalLayout_2.addWidget(self.zoompushButton)
        self.addNumberpushButton = QtGui.QPushButton(self.centralwidget)
        self.addNumberpushButton.setObjectName("addNumberpushButton")
        self.horizontalLayout_2.addWidget(self.addNumberpushButton)
        self.addStringpushButton = QtGui.QPushButton(self.centralwidget)
        self.addStringpushButton.setObjectName("addStringpushButton")
        self.horizontalLayout_2.addWidget(self.addStringpushButton)
        self.useEventscheckBox = QtGui.QCheckBox(self.centralwidget)
        self.useEventscheckBox.setObjectName("useEventscheckBox")
        self.horizontalLayout_2.addWidget(self.useEventscheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.language = QtGui.QComboBox(self.centralwidget)
        self.language.setMaximumSize(QtCore.QSize(85, 27))
        self.language.setObjectName("language")
        self.language.addItem("")
        self.language.addItem("")
        self.horizontalLayout_2.addWidget(self.language)
        self.updatepushButton = QtGui.QPushButton(self.centralwidget)
        self.updatepushButton.setEnabled(False)
        self.updatepushButton.setObjectName("updatepushButton")
        self.horizontalLayout_2.addWidget(self.updatepushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.Tabwi = QtGui.QTabWidget(self.centralwidget)
        self.Tabwi.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tabwi.setFont(font)
        self.Tabwi.setTabPosition(QtGui.QTabWidget.North)
        self.Tabwi.setTabShape(QtGui.QTabWidget.Rounded)
        self.Tabwi.setObjectName("Tabwi")
        self.program_text = QtGui.QWidget()
        self.program_text.setEnabled(True)
        self.program_text.setObjectName("program_text")
        self.horizontalLayout = QtGui.QHBoxLayout(self.program_text)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtGui.QLabel(self.program_text)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.textCode = QtGui.QTextEdit(self.program_text)
        self.textCode.setObjectName("textCode")
        self.verticalLayout_6.addWidget(self.textCode)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cameraFrame = QtGui.QFrame(self.program_text)
        self.cameraFrame.setMinimumSize(QtCore.QSize(320, 240))
        self.cameraFrame.setMaximumSize(QtCore.QSize(320, 240))
        self.cameraFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cameraFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.cameraFrame.setObjectName("cameraFrame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.cameraFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cameragraphicsView = QtGui.QGraphicsView(self.cameraFrame)
        self.cameragraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cameragraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cameragraphicsView.setObjectName("cameragraphicsView")
        self.horizontalLayout_3.addWidget(self.cameragraphicsView)
        self.verticalLayout_5.addWidget(self.cameraFrame)
        self.connectCameraRobotpushButton = QtGui.QPushButton(self.program_text)
        self.connectCameraRobotpushButton.setObjectName("connectCameraRobotpushButton")
        self.verticalLayout_5.addWidget(self.connectCameraRobotpushButton)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBoxLeterSize = QtGui.QSpinBox(self.program_text)
        self.spinBoxLeterSize.setMaximumSize(QtCore.QSize(61, 29))
        self.spinBoxLeterSize.setProperty("value", 12)
        self.spinBoxLeterSize.setObjectName("spinBoxLeterSize")
        self.gridLayout_2.addWidget(self.spinBoxLeterSize, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.program_text)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.program_text)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.stoptextPushButton = QtGui.QPushButton(self.program_text)
        self.stoptextPushButton.setEnabled(True)
        self.stoptextPushButton.setObjectName("stoptextPushButton")
        self.verticalLayout_17.addWidget(self.stoptextPushButton)
        self.startPRTextPushButton = QtGui.QPushButton(self.program_text)
        self.startPRTextPushButton.setObjectName("startPRTextPushButton")
        self.verticalLayout_17.addWidget(self.startPRTextPushButton)
        self.startSRTextPushButton = QtGui.QPushButton(self.program_text)
        self.startSRTextPushButton.setEnabled(True)
        self.startSRTextPushButton.setObjectName("startSRTextPushButton")
        self.verticalLayout_17.addWidget(self.startSRTextPushButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_17)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.Tabwi.addTab(self.program_text, "")
        self.program_visual = QtGui.QWidget()
        self.program_visual.setObjectName("program_visual")
        self.gridLayout = QtGui.QGridLayout(self.program_visual)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.program_visual)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.functions = QtGui.QTabWidget(self.splitter)
        self.functions.setEnabled(True)
        self.functions.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.functions.setFont(font)
        self.functions.setTabPosition(QtGui.QTabWidget.West)
        self.functions.setObjectName("functions")
        self.search = QtGui.QWidget()
        self.search.setObjectName("search")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.search)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.SearchlineEdit = QtGui.QLineEdit(self.search)
        self.SearchlineEdit.setObjectName("SearchlineEdit")
        self.verticalLayout_16.addWidget(self.SearchlineEdit)
        self.tableSearch = QtGui.QTableWidget(self.search)
        self.tableSearch.setShowGrid(False)
        self.tableSearch.setGridStyle(QtCore.Qt.NoPen)
        self.tableSearch.setObjectName("tableSearch")
        self.tableSearch.setColumnCount(0)
        self.tableSearch.setRowCount(0)
        self.tableSearch.horizontalHeader().setVisible(False)
        self.tableSearch.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tableSearch)
        self.functions.addTab(self.search, "")
        self.control = QtGui.QWidget()
        self.control.setObjectName("control")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.control)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.addWhenpushButton = QtGui.QPushButton(self.control)
        self.addWhenpushButton.setObjectName("addWhenpushButton")
        self.verticalLayout_12.addWidget(self.addWhenpushButton)
        self.deleteWhenpushButton = QtGui.QPushButton(self.control)
        self.deleteWhenpushButton.setEnabled(False)
        self.deleteWhenpushButton.setObjectName("deleteWhenpushButton")
        self.verticalLayout_12.addWidget(self.deleteWhenpushButton)
        self.tableControl = QtGui.QTableWidget(self.control)
        self.tableControl.setShowGrid(False)
        self.tableControl.setGridStyle(QtCore.Qt.NoPen)
        self.tableControl.setObjectName("tableControl")
        self.tableControl.setColumnCount(0)
        self.tableControl.setRowCount(0)
        self.verticalLayout_12.addWidget(self.tableControl)
        self.functions.addTab(self.control, "")
        self.express = QtGui.QWidget()
        self.express.setObjectName("express")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.express)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tableExpress = QtGui.QTableWidget(self.express)
        self.tableExpress.setShowGrid(False)
        self.tableExpress.setGridStyle(QtCore.Qt.NoPen)
        self.tableExpress.setObjectName("tableExpress")
        self.tableExpress.setColumnCount(0)
        self.tableExpress.setRowCount(0)
        self.verticalLayout_14.addWidget(self.tableExpress)
        self.functions.addTab(self.express, "")
        self.move = QtGui.QWidget()
        self.move.setObjectName("move")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.move)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tableMotor = QtGui.QTableWidget(self.move)
        self.tableMotor.setShowGrid(False)
        self.tableMotor.setGridStyle(QtCore.Qt.NoPen)
        self.tableMotor.setObjectName("tableMotor")
        self.tableMotor.setColumnCount(0)
        self.tableMotor.setRowCount(0)
        self.verticalLayout_11.addWidget(self.tableMotor)
        self.functions.addTab(self.move, "")
        self.sensors = QtGui.QWidget()
        self.sensors.setObjectName("sensors")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.sensors)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tablePerceptual = QtGui.QTableWidget(self.sensors)
        self.tablePerceptual.setShowGrid(False)
        self.tablePerceptual.setGridStyle(QtCore.Qt.NoPen)
        self.tablePerceptual.setObjectName("tablePerceptual")
        self.tablePerceptual.setColumnCount(0)
        self.tablePerceptual.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tablePerceptual)
        self.functions.addTab(self.sensors, "")
        self.propioperceptive = QtGui.QWidget()
        self.propioperceptive.setObjectName("propioperceptive")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.propioperceptive)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tablePropioperceptive = QtGui.QTableWidget(self.propioperceptive)
        self.tablePropioperceptive.setShowGrid(False)
        self.tablePropioperceptive.setGridStyle(QtCore.Qt.NoPen)
        self.tablePropioperceptive.setObjectName("tablePropioperceptive")
        self.tablePropioperceptive.setColumnCount(0)
        self.tablePropioperceptive.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tablePropioperceptive)
        self.functions.addTab(self.propioperceptive, "")
        self.operators = QtGui.QWidget()
        self.operators.setObjectName("operators")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.operators)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableOperadores = QtGui.QTableWidget(self.operators)
        self.tableOperadores.setShowGrid(False)
        self.tableOperadores.setGridStyle(QtCore.Qt.NoPen)
        self.tableOperadores.setObjectName("tableOperadores")
        self.tableOperadores.setColumnCount(0)
        self.tableOperadores.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableOperadores)
        self.functions.addTab(self.operators, "")
        self.variables = QtGui.QWidget()
        self.variables.setEnabled(True)
        self.variables.setObjectName("variables")
        self.verticalLayout = QtGui.QVBoxLayout(self.variables)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addVarPushButton = QtGui.QPushButton(self.variables)
        self.addVarPushButton.setEnabled(True)
        self.addVarPushButton.setObjectName("addVarPushButton")
        self.verticalLayout_2.addWidget(self.addVarPushButton)
        self.deleteVarPushButton = QtGui.QPushButton(self.variables)
        self.deleteVarPushButton.setEnabled(False)
        self.deleteVarPushButton.setObjectName("deleteVarPushButton")
        self.verticalLayout_2.addWidget(self.deleteVarPushButton)
        self.pushButton_6 = QtGui.QPushButton(self.variables)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tableVariables = QtGui.QTableWidget(self.variables)
        self.tableVariables.setShowGrid(False)
        self.tableVariables.setGridStyle(QtCore.Qt.NoPen)
        self.tableVariables.setObjectName("tableVariables")
        self.tableVariables.setColumnCount(0)
        self.tableVariables.setRowCount(0)
        self.verticalLayout.addWidget(self.tableVariables)
        self.functions.addTab(self.variables, "")
        self.user_funtions = QtGui.QWidget()
        self.user_funtions.setObjectName("user_funtions")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.user_funtions)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.createFunctionsPushButton = QtGui.QPushButton(self.user_funtions)
        self.createFunctionsPushButton.setEnabled(True)
        self.createFunctionsPushButton.setObjectName("createFunctionsPushButton")
        self.verticalLayout_8.addWidget(self.createFunctionsPushButton)
        self.deleteFuntionsPushButton = QtGui.QPushButton(self.user_funtions)
        self.deleteFuntionsPushButton.setEnabled(False)
        self.deleteFuntionsPushButton.setObjectName("deleteFuntionsPushButton")
        self.verticalLayout_8.addWidget(self.deleteFuntionsPushButton)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        self.tableUserfunctions = QtGui.QTableWidget(self.user_funtions)
        self.tableUserfunctions.setShowGrid(False)
        self.tableUserfunctions.setGridStyle(QtCore.Qt.NoPen)
        self.tableUserfunctions.setObjectName("tableUserfunctions")
        self.tableUserfunctions.setColumnCount(0)
        self.tableUserfunctions.setRowCount(0)
        self.verticalLayout_13.addWidget(self.tableUserfunctions)
        self.functions.addTab(self.user_funtions, "")
        self.others = QtGui.QWidget()
        self.others.setObjectName("others")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.others)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableOthers = QtGui.QTableWidget(self.others)
        self.tableOthers.setShowGrid(False)
        self.tableOthers.setGridStyle(QtCore.Qt.NoPen)
        self.tableOthers.setObjectName("tableOthers")
        self.tableOthers.setColumnCount(0)
        self.tableOthers.setRowCount(0)
        self.verticalLayout_15.addWidget(self.tableOthers)
        self.functions.addTab(self.others, "")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.block2textpushButton = QtGui.QPushButton(self.layoutWidget)
        self.block2textpushButton.setObjectName("block2textpushButton")
        self.horizontalLayout_4.addWidget(self.block2textpushButton)
        self.startPushButton = QtGui.QPushButton(self.layoutWidget)
        self.startPushButton.setMaximumSize(QtCore.QSize(16777215, 27))
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout_4.addWidget(self.startPushButton)
        self.startPRPushButton = QtGui.QPushButton(self.layoutWidget)
        self.startPRPushButton.setObjectName("startPRPushButton")
        self.horizontalLayout_4.addWidget(self.startPRPushButton)
        self.stopPushButton = QtGui.QPushButton(self.layoutWidget)
        self.stopPushButton.setMaximumSize(QtCore.QSize(16777215, 27))
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_4.addWidget(self.stopPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.Tabwi.addTab(self.program_visual, "")
        self.verticalLayout_4.addWidget(self.Tabwi)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools_robot = QtGui.QMenu(self.menubar)
        self.menuTools_robot.setObjectName("menuTools_robot")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuProyect = QtGui.QMenu(self.menubar)
        self.menuProyect.setObjectName("menuProyect")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_New_block = QtGui.QAction(MainWindow)
        self.actionCreate_New_block.setObjectName("actionCreate_New_block")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_Proyect = QtGui.QAction(MainWindow)
        self.actionOpen_Proyect.setObjectName("actionOpen_Proyect")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionStart_components = QtGui.QAction(MainWindow)
        self.actionStart_components.setObjectName("actionStart_components")
        self.actionReboot = QtGui.QAction(MainWindow)
        self.actionReboot.setObjectName("actionReboot")
        self.actionShutdown = QtGui.QAction(MainWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.actionStart_Simulator = QtGui.QAction(MainWindow)
        self.actionStart_Simulator.setObjectName("actionStart_Simulator")
        self.actionNew_project = QtGui.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionLoad_Library = QtGui.QAction(MainWindow)
        self.actionLoad_Library.setObjectName("actionLoad_Library")
        self.actionDownload_xmls = QtGui.QAction(MainWindow)
        self.actionDownload_xmls.setObjectName("actionDownload_xmls")
        self.actionChange_Libraries_path = QtGui.QAction(MainWindow)
        self.actionChange_Libraries_path.setObjectName("actionChange_Libraries_path")
        self.actionChange_Workspace = QtGui.QAction(MainWindow)
        self.actionChange_Workspace.setObjectName("actionChange_Workspace")
        self.actionOpen_Recent = QtGui.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionDownload_examples = QtGui.QAction(MainWindow)
        self.actionDownload_examples.setObjectName("actionDownload_examples")
        self.actionDownload_libraries = QtGui.QAction(MainWindow)
        self.actionDownload_libraries.setObjectName("actionDownload_libraries")
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionBlocks_to_text = QtGui.QAction(MainWindow)
        self.actionBlocks_to_text.setObjectName("actionBlocks_to_text")
        self.actionStart_simulated_robot = QtGui.QAction(MainWindow)
        self.actionStart_simulated_robot.setObjectName("actionStart_simulated_robot")
        self.actionStart_physical_robot = QtGui.QAction(MainWindow)
        self.actionStart_physical_robot.setObjectName("actionStart_physical_robot")
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionStop_Simulator = QtGui.QAction(MainWindow)
        self.actionStop_Simulator.setObjectName("actionStop_Simulator")
        self.actionStart_aprilTag = QtGui.QAction(MainWindow)
        self.actionStart_aprilTag.setObjectName("actionStart_aprilTag")
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCreate_New_block)
        self.menuFile.addAction(self.actionOpen_Proyect)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Library)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionChange_Libraries_path)
        self.menuFile.addAction(self.actionChange_Workspace)
        self.menuTools_robot.addAction(self.actionStart_Simulator)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionStart_components)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionReboot)
        self.menuTools_robot.addAction(self.actionShutdown)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionDownload_xmls)
        self.menuTools_robot.addAction(self.actionDownload_examples)
        self.menuTools_robot.addAction(self.actionDownload_libraries)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuProyect.addAction(self.actionBlocks_to_text)
        self.menuProyect.addAction(self.actionStart_simulated_robot)
        self.menuProyect.addAction(self.actionStart_physical_robot)
        self.menuProyect.addAction(self.actionStop)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProyect.menuAction())
        self.menubar.addAction(self.menuTools_robot.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabwi.setCurrentIndex(1)
        self.functions.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.openpushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.savepushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.zoompushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.addNumberpushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Number", None, QtGui.QApplication.UnicodeUTF8))
        self.addNumberpushButton.setText(QtGui.QApplication.translate("MainWindow", "Add Number", None, QtGui.QApplication.UnicodeUTF8))
        self.addStringpushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Add String", None, QtGui.QApplication.UnicodeUTF8))
        self.addStringpushButton.setText(QtGui.QApplication.translate("MainWindow", "Add String", None, QtGui.QApplication.UnicodeUTF8))
        self.useEventscheckBox.setText(QtGui.QApplication.translate("MainWindow", "Use Events", None, QtGui.QApplication.UnicodeUTF8))
        self.language.setItemText(0, QtGui.QApplication.translate("MainWindow", "ES", None, QtGui.QApplication.UnicodeUTF8))
        self.language.setItemText(1, QtGui.QApplication.translate("MainWindow", "EN", None, QtGui.QApplication.UnicodeUTF8))
        self.updatepushButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabwi.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>H</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.connectCameraRobotpushButton.setText(QtGui.QApplication.translate("MainWindow", "Connect Camera Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Size Leter", None, QtGui.QApplication.UnicodeUTF8))
        self.stoptextPushButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.startPRTextPushButton.setText(QtGui.QApplication.translate("MainWindow", "Start (physical robot)", None, QtGui.QApplication.UnicodeUTF8))
        self.startSRTextPushButton.setText(QtGui.QApplication.translate("MainWindow", "Start (simulated robot)", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.program_text), QtGui.QApplication.translate("MainWindow", "Text Code", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.search), QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.addWhenpushButton.setText(QtGui.QApplication.translate("MainWindow", "Add When", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteWhenpushButton.setText(QtGui.QApplication.translate("MainWindow", "Delete When", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.control), QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.express), QtGui.QApplication.translate("MainWindow", "Expressions", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.move), QtGui.QApplication.translate("MainWindow", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.sensors), QtGui.QApplication.translate("MainWindow", "Perceptual", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.propioperceptive), QtGui.QApplication.translate("MainWindow", "Proprioceptive", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.operators), QtGui.QApplication.translate("MainWindow", "Operators", None, QtGui.QApplication.UnicodeUTF8))
        self.addVarPushButton.setText(QtGui.QApplication.translate("MainWindow", "Add Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteVarPushButton.setText(QtGui.QApplication.translate("MainWindow", "Delete Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Add List", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.variables), QtGui.QApplication.translate("MainWindow", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.createFunctionsPushButton.setText(QtGui.QApplication.translate("MainWindow", "Create Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteFuntionsPushButton.setText(QtGui.QApplication.translate("MainWindow", "Delete Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.user_funtions), QtGui.QApplication.translate("MainWindow", "User functions", None, QtGui.QApplication.UnicodeUTF8))
        self.functions.setTabText(self.functions.indexOf(self.others), QtGui.QApplication.translate("MainWindow", "Others", None, QtGui.QApplication.UnicodeUTF8))
        self.block2textpushButton.setText(QtGui.QApplication.translate("MainWindow", "Blocks to text", None, QtGui.QApplication.UnicodeUTF8))
        self.startPushButton.setText(QtGui.QApplication.translate("MainWindow", "Start (simulated robot)", None, QtGui.QApplication.UnicodeUTF8))
        self.startPRPushButton.setText(QtGui.QApplication.translate("MainWindow", "Start (physical robot)", None, QtGui.QApplication.UnicodeUTF8))
        self.stopPushButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.program_visual), QtGui.QApplication.translate("MainWindow", "LearnBlock", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools_robot.setTitle(QtGui.QApplication.translate("MainWindow", "tools robot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProyect.setTitle(QtGui.QApplication.translate("MainWindow", "Proyect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_New_block.setText(QtGui.QApplication.translate("MainWindow", "Create New block", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save Proyect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Proyect.setText(QtGui.QApplication.translate("MainWindow", "Open Proyect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Proyect.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_components.setText(QtGui.QApplication.translate("MainWindow", "Start components", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_components.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReboot.setText(QtGui.QApplication.translate("MainWindow", "Reboot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReboot.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShutdown.setText(QtGui.QApplication.translate("MainWindow", "Shutdown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShutdown.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Simulator.setText(QtGui.QApplication.translate("MainWindow", "Start Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Simulator.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_project.setText(QtGui.QApplication.translate("MainWindow", "New project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Library.setText(QtGui.QApplication.translate("MainWindow", "Load Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Library.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload_xmls.setText(QtGui.QApplication.translate("MainWindow", "Download xmls", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload_xmls.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_Libraries_path.setText(QtGui.QApplication.translate("MainWindow", "Change Libraries path", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_Libraries_path.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_Workspace.setText(QtGui.QApplication.translate("MainWindow", "Change Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_Workspace.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Recent.setText(QtGui.QApplication.translate("MainWindow", "Open Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload_examples.setText(QtGui.QApplication.translate("MainWindow", "Download examples", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload_libraries.setText(QtGui.QApplication.translate("MainWindow", "Download libraries", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlocks_to_text.setText(QtGui.QApplication.translate("MainWindow", "Blocks to text", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlocks_to_text.setShortcut(QtGui.QApplication.translate("MainWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_simulated_robot.setText(QtGui.QApplication.translate("MainWindow", "Start (simulated robot)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_simulated_robot.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_physical_robot.setText(QtGui.QApplication.translate("MainWindow", "Start (physical robot)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_physical_robot.setShortcut(QtGui.QApplication.translate("MainWindow", "F6", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setShortcut(QtGui.QApplication.translate("MainWindow", "F7", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Simulator.setText(QtGui.QApplication.translate("MainWindow", "Stop Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_aprilTag.setText(QtGui.QApplication.translate("MainWindow", "Start aprilTag", None, QtGui.QApplication.UnicodeUTF8))

