# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Learnblock.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(955, 790)
        MainWindow.setCursor(QCursor(Qt.ArrowCursor))
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionCreate_New_block = QAction(MainWindow)
        self.actionCreate_New_block.setObjectName(u"actionCreate_New_block")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionOpen_Project = QAction(MainWindow)
        self.actionOpen_Project.setObjectName(u"actionOpen_Project")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionStart_components = QAction(MainWindow)
        self.actionStart_components.setObjectName(u"actionStart_components")
        self.actionReboot = QAction(MainWindow)
        self.actionReboot.setObjectName(u"actionReboot")
        self.actionShutdown = QAction(MainWindow)
        self.actionShutdown.setObjectName(u"actionShutdown")
        self.actionStart_Simulator = QAction(MainWindow)
        self.actionStart_Simulator.setObjectName(u"actionStart_Simulator")
        self.actionNew_project = QAction(MainWindow)
        self.actionNew_project.setObjectName(u"actionNew_project")
        self.actionLoad_Library = QAction(MainWindow)
        self.actionLoad_Library.setObjectName(u"actionLoad_Library")
        self.actionDownload_xmls = QAction(MainWindow)
        self.actionDownload_xmls.setObjectName(u"actionDownload_xmls")
        self.actionChange_Libraries_path = QAction(MainWindow)
        self.actionChange_Libraries_path.setObjectName(u"actionChange_Libraries_path")
        self.actionChange_Workspace = QAction(MainWindow)
        self.actionChange_Workspace.setObjectName(u"actionChange_Workspace")
        self.actionOpen_Recent = QAction(MainWindow)
        self.actionOpen_Recent.setObjectName(u"actionOpen_Recent")
        self.actionDownload_examples = QAction(MainWindow)
        self.actionDownload_examples.setObjectName(u"actionDownload_examples")
        self.actionDownload_libraries = QAction(MainWindow)
        self.actionDownload_libraries.setObjectName(u"actionDownload_libraries")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionBlocks_to_text = QAction(MainWindow)
        self.actionBlocks_to_text.setObjectName(u"actionBlocks_to_text")
        self.actionStart_simulated_robot = QAction(MainWindow)
        self.actionStart_simulated_robot.setObjectName(u"actionStart_simulated_robot")
        self.actionStart_physical_robot = QAction(MainWindow)
        self.actionStart_physical_robot.setObjectName(u"actionStart_physical_robot")
        self.actionStop = QAction(MainWindow)
        self.actionStop.setObjectName(u"actionStop")
        self.actionStop_Simulator = QAction(MainWindow)
        self.actionStop_Simulator.setObjectName(u"actionStop_Simulator")
        self.actionStart_aprilTag = QAction(MainWindow)
        self.actionStart_aprilTag.setObjectName(u"actionStart_aprilTag")
        self.actionDuplicate = QAction(MainWindow)
        self.actionDuplicate.setObjectName(u"actionDuplicate")
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionExport_Block = QAction(MainWindow)
        self.actionExport_Block.setObjectName(u"actionExport_Block")
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionAdd_client_robot = QAction(MainWindow)
        self.actionAdd_client_robot.setObjectName(u"actionAdd_client_robot")
        self.actionStart = QAction(MainWindow)
        self.actionStart.setObjectName(u"actionStart")
        self.actionDark = QAction(MainWindow)
        self.actionDark.setObjectName(u"actionDark")
        self.actionDark.setCheckable(True)
        self.actionDark.setChecked(False)
        self.actionDictionary_Tags = QAction(MainWindow)
        self.actionDictionary_Tags.setObjectName(u"actionDictionary_Tags")
        self.actionLoad_Sets_of_Blocks = QAction(MainWindow)
        self.actionLoad_Sets_of_Blocks.setObjectName(u"actionLoad_Sets_of_Blocks")
        self.actionSelect_Visible_Blocks = QAction(MainWindow)
        self.actionSelect_Visible_Blocks.setObjectName(u"actionSelect_Visible_Blocks")
        self.actionSave_Visible_Blocks = QAction(MainWindow)
        self.actionSave_Visible_Blocks.setObjectName(u"actionSave_Visible_Blocks")
        self.actionLoad_Block_Text_Code = QAction(MainWindow)
        self.actionLoad_Block_Text_Code.setObjectName(u"actionLoad_Block_Text_Code")
        self.actionSave_Block_Text_Code = QAction(MainWindow)
        self.actionSave_Block_Text_Code.setObjectName(u"actionSave_Block_Text_Code")
        self.actionLoad_Python_Code = QAction(MainWindow)
        self.actionLoad_Python_Code.setObjectName(u"actionLoad_Python_Code")
        self.actionSave_Python_Code = QAction(MainWindow)
        self.actionSave_Python_Code.setObjectName(u"actionSave_Python_Code")
        self.actionAdd_Set_of_Blocks = QAction(MainWindow)
        self.actionAdd_Set_of_Blocks.setObjectName(u"actionAdd_Set_of_Blocks")
        self.actionConfigure_Robot = QAction(MainWindow)
        self.actionConfigure_Robot.setObjectName(u"actionConfigure_Robot")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_4 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.openpushButton = QPushButton(self.centralwidget)
        self.openpushButton.setObjectName(u"openpushButton")
        self.openpushButton.setFlat(True)

        self.horizontalLayout_2.addWidget(self.openpushButton)

        self.savepushButton = QPushButton(self.centralwidget)
        self.savepushButton.setObjectName(u"savepushButton")
        self.savepushButton.setFlat(True)

        self.horizontalLayout_2.addWidget(self.savepushButton)

        self.zoompushButton = QPushButton(self.centralwidget)
        self.zoompushButton.setObjectName(u"zoompushButton")
        self.zoompushButton.setCheckable(True)
        self.zoompushButton.setFlat(True)

        self.horizontalLayout_2.addWidget(self.zoompushButton)

        self.addNumberpushButton = QPushButton(self.centralwidget)
        self.addNumberpushButton.setObjectName(u"addNumberpushButton")

        self.horizontalLayout_2.addWidget(self.addNumberpushButton)

        self.addStringpushButton = QPushButton(self.centralwidget)
        self.addStringpushButton.setObjectName(u"addStringpushButton")

        self.horizontalLayout_2.addWidget(self.addStringpushButton)

        self.useEventscheckBox = QCheckBox(self.centralwidget)
        self.useEventscheckBox.setObjectName(u"useEventscheckBox")

        self.horizontalLayout_2.addWidget(self.useEventscheckBox)

        self.clientscomboBox = QComboBox(self.centralwidget)
        self.clientscomboBox.addItem(u"EBO")
        self.clientscomboBox.setObjectName(u"clientscomboBox")
        self.clientscomboBox.setCurrentText(u"EBO")

        self.horizontalLayout_2.addWidget(self.clientscomboBox)

        self.addClientPushButton = QPushButton(self.centralwidget)
        self.addClientPushButton.setObjectName(u"addClientPushButton")

        self.horizontalLayout_2.addWidget(self.addClientPushButton)

        self.configRobotPushButton = QPushButton(self.centralwidget)
        self.configRobotPushButton.setObjectName(u"configRobotPushButton")

        self.horizontalLayout_2.addWidget(self.configRobotPushButton)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.language = QComboBox(self.centralwidget)
        self.language.addItem("")
        self.language.addItem("")
        self.language.setObjectName(u"language")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language.sizePolicy().hasHeightForWidth())
        self.language.setSizePolicy(sizePolicy)
        self.language.setMaximumSize(QSize(16777215, 16777215))

        self.horizontalLayout_2.addWidget(self.language)

        self.updatepushButton = QPushButton(self.centralwidget)
        self.updatepushButton.setObjectName(u"updatepushButton")
        self.updatepushButton.setEnabled(False)

        self.horizontalLayout_2.addWidget(self.updatepushButton)


        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.Tabwi = QTabWidget(self.centralwidget)
        self.Tabwi.setObjectName(u"Tabwi")
        self.Tabwi.setEnabled(True)
        font = QFont()
        font.setPointSize(10)
        self.Tabwi.setFont(font)
        self.Tabwi.setTabPosition(QTabWidget.North)
        self.Tabwi.setTabShape(QTabWidget.Rounded)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.horizontalLayout_5 = QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.verticalLayout_18 = QVBoxLayout()
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")

        self.verticalLayout_18.addWidget(self.label_4)

        self.pythonCode = QTextEdit(self.tab)
        self.pythonCode.setObjectName(u"pythonCode")

        self.verticalLayout_18.addWidget(self.pythonCode)


        self.horizontalLayout_5.addLayout(self.verticalLayout_18)

        self.verticalLayout_20 = QVBoxLayout()
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.spinBoxPythonSize = QSpinBox(self.tab)
        self.spinBoxPythonSize.setObjectName(u"spinBoxPythonSize")
        self.spinBoxPythonSize.setMaximumSize(QSize(61, 29))
        self.spinBoxPythonSize.setValue(12)

        self.gridLayout_3.addWidget(self.spinBoxPythonSize, 1, 1, 1, 1)

        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)

        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)


        self.verticalLayout_20.addLayout(self.gridLayout_3)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_20.addItem(self.verticalSpacer_2)

        self.verticalLayout_19 = QVBoxLayout()
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.startPythonPushButton = QPushButton(self.tab)
        self.startPythonPushButton.setObjectName(u"startPythonPushButton")

        self.verticalLayout_19.addWidget(self.startPythonPushButton)

        self.stopPythonPushButton = QPushButton(self.tab)
        self.stopPythonPushButton.setObjectName(u"stopPythonPushButton")
        self.stopPythonPushButton.setEnabled(True)

        self.verticalLayout_19.addWidget(self.stopPythonPushButton)


        self.verticalLayout_20.addLayout(self.verticalLayout_19)


        self.horizontalLayout_5.addLayout(self.verticalLayout_20)

        self.Tabwi.addTab(self.tab, "")
        self.program_text = QWidget()
        self.program_text.setObjectName(u"program_text")
        self.program_text.setEnabled(True)
        self.horizontalLayout = QHBoxLayout(self.program_text)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.label_3 = QLabel(self.program_text)
        self.label_3.setObjectName(u"label_3")

        self.verticalLayout_6.addWidget(self.label_3)

        self.textCodeSplitter = QSplitter(self.program_text)
        self.textCodeSplitter.setObjectName(u"textCodeSplitter")
        self.textCodeSplitter.setOrientation(Qt.Vertical)
        self.textCode = QTextEdit(self.textCodeSplitter)
        self.textCode.setObjectName(u"textCode")
        self.textCodeSplitter.addWidget(self.textCode)
        self.notificationList = QListWidget(self.textCodeSplitter)
        self.notificationList.setObjectName(u"notificationList")
        self.notificationList.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.textCodeSplitter.addWidget(self.notificationList)

        self.verticalLayout_6.addWidget(self.textCodeSplitter)


        self.horizontalLayout.addLayout(self.verticalLayout_6)

        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.cameraFrame = QFrame(self.program_text)
        self.cameraFrame.setObjectName(u"cameraFrame")
        self.cameraFrame.setMinimumSize(QSize(320, 240))
        self.cameraFrame.setMaximumSize(QSize(320, 240))
        self.cameraFrame.setFrameShape(QFrame.StyledPanel)
        self.cameraFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.cameraFrame)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.cameragraphicsView = QGraphicsView(self.cameraFrame)
        self.cameragraphicsView.setObjectName(u"cameragraphicsView")
        self.cameragraphicsView.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.cameragraphicsView.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

        self.horizontalLayout_3.addWidget(self.cameragraphicsView)


        self.verticalLayout_5.addWidget(self.cameraFrame)

        self.connectCameraRobotpushButton = QPushButton(self.program_text)
        self.connectCameraRobotpushButton.setObjectName(u"connectCameraRobotpushButton")

        self.verticalLayout_5.addWidget(self.connectCameraRobotpushButton)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.spinBoxLeterSize = QSpinBox(self.program_text)
        self.spinBoxLeterSize.setObjectName(u"spinBoxLeterSize")
        self.spinBoxLeterSize.setMaximumSize(QSize(61, 29))
        self.spinBoxLeterSize.setValue(12)

        self.gridLayout_2.addWidget(self.spinBoxLeterSize, 1, 1, 1, 1)

        self.label = QLabel(self.program_text)
        self.label.setObjectName(u"label")

        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1)

        self.label_2 = QLabel(self.program_text)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)


        self.verticalLayout_5.addLayout(self.gridLayout_2)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_5.addItem(self.verticalSpacer)

        self.verticalLayout_17 = QVBoxLayout()
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.bt2pythonpushButton = QPushButton(self.program_text)
        self.bt2pythonpushButton.setObjectName(u"bt2pythonpushButton")

        self.verticalLayout_17.addWidget(self.bt2pythonpushButton)

        self.starttextPushButton = QPushButton(self.program_text)
        self.starttextPushButton.setObjectName(u"starttextPushButton")

        self.verticalLayout_17.addWidget(self.starttextPushButton)

        self.stoptextPushButton = QPushButton(self.program_text)
        self.stoptextPushButton.setObjectName(u"stoptextPushButton")
        self.stoptextPushButton.setEnabled(True)

        self.verticalLayout_17.addWidget(self.stoptextPushButton)


        self.verticalLayout_5.addLayout(self.verticalLayout_17)


        self.horizontalLayout.addLayout(self.verticalLayout_5)

        self.Tabwi.addTab(self.program_text, "")
        self.program_visual = QWidget()
        self.program_visual.setObjectName(u"program_visual")
        self.gridLayout = QGridLayout(self.program_visual)
        self.gridLayout.setObjectName(u"gridLayout")
        self.splitter = QSplitter(self.program_visual)
        self.splitter.setObjectName(u"splitter")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy1)
        self.splitter.setOrientation(Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(6)
        self.splitter.setChildrenCollapsible(True)
        self.functions = QTabWidget(self.splitter)
        self.functions.setObjectName(u"functions")
        self.functions.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.functions.sizePolicy().hasHeightForWidth())
        self.functions.setSizePolicy(sizePolicy1)
        self.functions.setMaximumSize(QSize(16777215, 16777215))
        self.functions.setBaseSize(QSize(229, 0))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setWeight(50)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        self.functions.setFont(font1)
        self.functions.setTabPosition(QTabWidget.West)
        self.search = QWidget()
        self.search.setObjectName(u"search")
        self.verticalLayout_16 = QVBoxLayout(self.search)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.SearchlineEdit = QLineEdit(self.search)
        self.SearchlineEdit.setObjectName(u"SearchlineEdit")

        self.verticalLayout_16.addWidget(self.SearchlineEdit)

        self.tableSearch = QTableWidget(self.search)
        self.tableSearch.setObjectName(u"tableSearch")
        self.tableSearch.setShowGrid(False)
        self.tableSearch.setGridStyle(Qt.NoPen)
        self.tableSearch.horizontalHeader().setVisible(False)
        self.tableSearch.verticalHeader().setVisible(False)

        self.verticalLayout_16.addWidget(self.tableSearch)

        self.functions.addTab(self.search, "")
        self.control = QWidget()
        self.control.setObjectName(u"control")
        self.verticalLayout_12 = QVBoxLayout(self.control)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.addWhenpushButton = QPushButton(self.control)
        self.addWhenpushButton.setObjectName(u"addWhenpushButton")

        self.verticalLayout_12.addWidget(self.addWhenpushButton)

        self.deleteWhenpushButton = QPushButton(self.control)
        self.deleteWhenpushButton.setObjectName(u"deleteWhenpushButton")
        self.deleteWhenpushButton.setEnabled(False)

        self.verticalLayout_12.addWidget(self.deleteWhenpushButton)

        self.tableControl = QTableWidget(self.control)
        self.tableControl.setObjectName(u"tableControl")
        self.tableControl.setShowGrid(False)
        self.tableControl.setGridStyle(Qt.NoPen)

        self.verticalLayout_12.addWidget(self.tableControl)

        self.functions.addTab(self.control, "")
        self.operators = QWidget()
        self.operators.setObjectName(u"operators")
        self.verticalLayout_7 = QVBoxLayout(self.operators)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.tableOperadores = QTableWidget(self.operators)
        self.tableOperadores.setObjectName(u"tableOperadores")
        self.tableOperadores.setShowGrid(False)
        self.tableOperadores.setGridStyle(Qt.NoPen)

        self.verticalLayout_7.addWidget(self.tableOperadores)

        self.functions.addTab(self.operators, "")
        self.variables = QWidget()
        self.variables.setObjectName(u"variables")
        self.variables.setEnabled(True)
        self.verticalLayout = QVBoxLayout(self.variables)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.addVarPushButton = QPushButton(self.variables)
        self.addVarPushButton.setObjectName(u"addVarPushButton")
        self.addVarPushButton.setEnabled(True)

        self.verticalLayout_2.addWidget(self.addVarPushButton)

        self.deleteVarPushButton = QPushButton(self.variables)
        self.deleteVarPushButton.setObjectName(u"deleteVarPushButton")
        self.deleteVarPushButton.setEnabled(False)

        self.verticalLayout_2.addWidget(self.deleteVarPushButton)

        self.pushButton_6 = QPushButton(self.variables)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setEnabled(False)

        self.verticalLayout_2.addWidget(self.pushButton_6)


        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.tableVariables = QTableWidget(self.variables)
        self.tableVariables.setObjectName(u"tableVariables")
        self.tableVariables.setShowGrid(False)
        self.tableVariables.setGridStyle(Qt.NoPen)

        self.verticalLayout.addWidget(self.tableVariables)

        self.functions.addTab(self.variables, "")
        self.user_funtions = QWidget()
        self.user_funtions.setObjectName(u"user_funtions")
        self.verticalLayout_13 = QVBoxLayout(self.user_funtions)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.createFunctionsPushButton = QPushButton(self.user_funtions)
        self.createFunctionsPushButton.setObjectName(u"createFunctionsPushButton")
        self.createFunctionsPushButton.setEnabled(True)

        self.verticalLayout_8.addWidget(self.createFunctionsPushButton)

        self.deleteFuntionsPushButton = QPushButton(self.user_funtions)
        self.deleteFuntionsPushButton.setObjectName(u"deleteFuntionsPushButton")
        self.deleteFuntionsPushButton.setEnabled(False)

        self.verticalLayout_8.addWidget(self.deleteFuntionsPushButton)


        self.verticalLayout_13.addLayout(self.verticalLayout_8)

        self.tableUserfunctions = QTableWidget(self.user_funtions)
        self.tableUserfunctions.setObjectName(u"tableUserfunctions")
        self.tableUserfunctions.setShowGrid(False)
        self.tableUserfunctions.setGridStyle(Qt.NoPen)

        self.verticalLayout_13.addWidget(self.tableUserfunctions)

        self.functions.addTab(self.user_funtions, "")
        self.splitter.addWidget(self.functions)
        self.layoutWidget = QWidget(self.splitter)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.layoutWidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)

        self.verticalLayout_3.addWidget(self.frame)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.block2textpushButton = QPushButton(self.layoutWidget)
        self.block2textpushButton.setObjectName(u"block2textpushButton")

        self.horizontalLayout_4.addWidget(self.block2textpushButton)

        self.startpushButton = QPushButton(self.layoutWidget)
        self.startpushButton.setObjectName(u"startpushButton")

        self.horizontalLayout_4.addWidget(self.startpushButton)

        self.stopPushButton = QPushButton(self.layoutWidget)
        self.stopPushButton.setObjectName(u"stopPushButton")
        self.stopPushButton.setMaximumSize(QSize(16777215, 27))

        self.horizontalLayout_4.addWidget(self.stopPushButton)


        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.splitter.addWidget(self.layoutWidget)

        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.Tabwi.addTab(self.program_visual, "")

        self.verticalLayout_4.addWidget(self.Tabwi)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 955, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuTools_robot = QMenu(self.menubar)
        self.menuTools_robot.setObjectName(u"menuTools_robot")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuTheme = QMenu(self.menuEdit)
        self.menuTheme.setObjectName(u"menuTheme")
        self.menuProject = QMenu(self.menubar)
        self.menuProject.setObjectName(u"menuProject")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuBlocks = QMenu(self.menubar)
        self.menuBlocks.setObjectName(u"menuBlocks")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.position = QLabel(self.statusbar)
        self.position.setObjectName(u"position")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuBlocks.menuAction())
        self.menubar.addAction(self.menuTools_robot.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Block_Text_Code)
        self.menuFile.addAction(self.actionSave_Block_Text_Code)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Python_Code)
        self.menuFile.addAction(self.actionSave_Python_Code)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Library)
        self.menuFile.addAction(self.actionChange_Libraries_path)
        self.menuFile.addAction(self.actionChange_Workspace)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools_robot.addAction(self.actionStart_Simulator)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionStart_components)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionReboot)
        self.menuTools_robot.addAction(self.actionShutdown)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionAdd_client_robot)
        self.menuTools_robot.addAction(self.actionConfigure_Robot)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionDownload_xmls)
        self.menuTools_robot.addAction(self.actionDownload_examples)
        self.menuTools_robot.addAction(self.actionDownload_libraries)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuEdit.addAction(self.actionEdit)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionExport_Block)
        self.menuEdit.addAction(self.menuTheme.menuAction())
        self.menuEdit.addAction(self.actionDictionary_Tags)
        self.menuTheme.addAction(self.actionDark)
        self.menuProject.addAction(self.actionBlocks_to_text)
        self.menuProject.addAction(self.actionStart)
        self.menuProject.addAction(self.actionStop)
        self.menuHelp.addAction(self.actionHelp)
        self.menuBlocks.addAction(self.actionCreate_New_block)
        self.menuBlocks.addSeparator()
        self.menuBlocks.addAction(self.actionLoad_Sets_of_Blocks)
        self.menuBlocks.addAction(self.actionAdd_Set_of_Blocks)
        self.menuBlocks.addAction(self.actionSelect_Visible_Blocks)
        self.menuBlocks.addAction(self.actionSave_Visible_Blocks)

        self.retranslateUi(MainWindow)

        self.language.setCurrentIndex(1)
        self.Tabwi.setCurrentIndex(2)
        self.functions.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionCreate_New_block.setText(QCoreApplication.translate("MainWindow", u"Create New Block", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save Project", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen_Project.setText(QCoreApplication.translate("MainWindow", u"Open Project", None))
#if QT_CONFIG(shortcut)
        self.actionOpen_Project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionStart_components.setText(QCoreApplication.translate("MainWindow", u"Start EBO Components", None))
#if QT_CONFIG(shortcut)
        self.actionStart_components.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+1", None))
#endif // QT_CONFIG(shortcut)
        self.actionReboot.setText(QCoreApplication.translate("MainWindow", u"Reboot EBO", None))
#if QT_CONFIG(shortcut)
        self.actionReboot.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+2", None))
#endif // QT_CONFIG(shortcut)
        self.actionShutdown.setText(QCoreApplication.translate("MainWindow", u"Shutdown EBO", None))
#if QT_CONFIG(shortcut)
        self.actionShutdown.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+3", None))
#endif // QT_CONFIG(shortcut)
        self.actionStart_Simulator.setText(QCoreApplication.translate("MainWindow", u"Start EBO Simulator", None))
#if QT_CONFIG(shortcut)
        self.actionStart_Simulator.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+4", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew_project.setText(QCoreApplication.translate("MainWindow", u"New Project", None))
#if QT_CONFIG(shortcut)
        self.actionNew_project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoad_Library.setText(QCoreApplication.translate("MainWindow", u"Load Library", None))
#if QT_CONFIG(shortcut)
        self.actionLoad_Library.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionDownload_xmls.setText(QCoreApplication.translate("MainWindow", u"Download xmls", None))
#if QT_CONFIG(shortcut)
        self.actionDownload_xmls.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+5", None))
#endif // QT_CONFIG(shortcut)
        self.actionChange_Libraries_path.setText(QCoreApplication.translate("MainWindow", u"Change Path of Libraries", None))
#if QT_CONFIG(shortcut)
        self.actionChange_Libraries_path.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionChange_Workspace.setText(QCoreApplication.translate("MainWindow", u"Change Workspace", None))
#if QT_CONFIG(shortcut)
        self.actionChange_Workspace.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+W", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen_Recent.setText(QCoreApplication.translate("MainWindow", u"Open Recent", None))
        self.actionDownload_examples.setText(QCoreApplication.translate("MainWindow", u"Download examples", None))
        self.actionDownload_libraries.setText(QCoreApplication.translate("MainWindow", u"Download libraries", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionBlocks_to_text.setText(QCoreApplication.translate("MainWindow", u"Blocks to text", None))
#if QT_CONFIG(shortcut)
        self.actionBlocks_to_text.setShortcut(QCoreApplication.translate("MainWindow", u"F4", None))
#endif // QT_CONFIG(shortcut)
        self.actionStart_simulated_robot.setText(QCoreApplication.translate("MainWindow", u"Start (simulated robot)", None))
#if QT_CONFIG(shortcut)
        self.actionStart_simulated_robot.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionStart_physical_robot.setText(QCoreApplication.translate("MainWindow", u"Start (physical robot)", None))
#if QT_CONFIG(shortcut)
        self.actionStart_physical_robot.setShortcut(QCoreApplication.translate("MainWindow", u"F6", None))
#endif // QT_CONFIG(shortcut)
        self.actionStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
#if QT_CONFIG(shortcut)
        self.actionStop.setShortcut(QCoreApplication.translate("MainWindow", u"F7", None))
#endif // QT_CONFIG(shortcut)
        self.actionStop_Simulator.setText(QCoreApplication.translate("MainWindow", u"Stop Simulator", None))
        self.actionStart_aprilTag.setText(QCoreApplication.translate("MainWindow", u"Start aprilTag", None))
        self.actionDuplicate.setText(QCoreApplication.translate("MainWindow", u"Duplicate", None))
#if QT_CONFIG(shortcut)
        self.actionDuplicate.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
#if QT_CONFIG(shortcut)
        self.actionEdit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
#if QT_CONFIG(shortcut)
        self.actionDelete.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport_Block.setText(QCoreApplication.translate("MainWindow", u"Export Block", None))
#if QT_CONFIG(shortcut)
        self.actionExport_Block.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
#if QT_CONFIG(shortcut)
        self.actionHelp.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionAdd_client_robot.setText(QCoreApplication.translate("MainWindow", u"Add Robot Client", None))
        self.actionStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.actionDark.setText(QCoreApplication.translate("MainWindow", u"Dark", None))
        self.actionDictionary_Tags.setText(QCoreApplication.translate("MainWindow", u"Dictionary of Tags", None))
        self.actionLoad_Sets_of_Blocks.setText(QCoreApplication.translate("MainWindow", u"Load Sets of Blocks", None))
        self.actionSelect_Visible_Blocks.setText(QCoreApplication.translate("MainWindow", u"Select Visible Blocks", None))
        self.actionSave_Visible_Blocks.setText(QCoreApplication.translate("MainWindow", u"Save Visible Blocks", None))
        self.actionLoad_Block_Text_Code.setText(QCoreApplication.translate("MainWindow", u"Load Block-Text Code", None))
        self.actionSave_Block_Text_Code.setText(QCoreApplication.translate("MainWindow", u"Save Block-Text Code", None))
        self.actionLoad_Python_Code.setText(QCoreApplication.translate("MainWindow", u"Load Python Code", None))
        self.actionSave_Python_Code.setText(QCoreApplication.translate("MainWindow", u"Save Python Code", None))
        self.actionAdd_Set_of_Blocks.setText(QCoreApplication.translate("MainWindow", u"Add Set of Blocks", None))
        self.actionConfigure_Robot.setText(QCoreApplication.translate("MainWindow", u"Configure Robot", None))
#if QT_CONFIG(tooltip)
        self.openpushButton.setToolTip(QCoreApplication.translate("MainWindow", u"Open", None))
#endif // QT_CONFIG(tooltip)
        self.openpushButton.setText("")
#if QT_CONFIG(tooltip)
        self.savepushButton.setToolTip(QCoreApplication.translate("MainWindow", u"Save", None))
#endif // QT_CONFIG(tooltip)
        self.savepushButton.setText("")
#if QT_CONFIG(tooltip)
        self.zoompushButton.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom", None))
#endif // QT_CONFIG(tooltip)
        self.zoompushButton.setText("")
#if QT_CONFIG(tooltip)
        self.addNumberpushButton.setToolTip(QCoreApplication.translate("MainWindow", u"Add Number", None))
#endif // QT_CONFIG(tooltip)
        self.addNumberpushButton.setText(QCoreApplication.translate("MainWindow", u"Add Number", None))
#if QT_CONFIG(tooltip)
        self.addStringpushButton.setToolTip(QCoreApplication.translate("MainWindow", u"Add String", None))
#endif // QT_CONFIG(tooltip)
        self.addStringpushButton.setText(QCoreApplication.translate("MainWindow", u"Add String", None))
        self.useEventscheckBox.setText(QCoreApplication.translate("MainWindow", u"Use Events", None))

        self.addClientPushButton.setText(QCoreApplication.translate("MainWindow", u"Add Robot", None))
        self.configRobotPushButton.setText(QCoreApplication.translate("MainWindow", u"Configure Robot", None))
        self.language.setItemText(0, QCoreApplication.translate("MainWindow", u"ES", None))
        self.language.setItemText(1, QCoreApplication.translate("MainWindow", u"EN", None))

        self.updatepushButton.setText(QCoreApplication.translate("MainWindow", u"Update", None))
#if QT_CONFIG(whatsthis)
        self.Tabwi.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>H</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Program", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"px", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Size Leter", None))
        self.startPythonPushButton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.stopPythonPushButton.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Python", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Program", None))
        self.connectCameraRobotpushButton.setText(QCoreApplication.translate("MainWindow", u"Connect Camera Robot", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"px", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Size Leter", None))
        self.bt2pythonpushButton.setText(QCoreApplication.translate("MainWindow", u"Block-Text to Python", None))
        self.starttextPushButton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.stoptextPushButton.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.program_text), QCoreApplication.translate("MainWindow", u"Block-Text", None))
        self.functions.setTabText(self.functions.indexOf(self.search), QCoreApplication.translate("MainWindow", u"Search", None))
        self.addWhenpushButton.setText(QCoreApplication.translate("MainWindow", u"Add When", None))
        self.deleteWhenpushButton.setText(QCoreApplication.translate("MainWindow", u"Delete When", None))
        self.functions.setTabText(self.functions.indexOf(self.control), QCoreApplication.translate("MainWindow", u"Control", None))
        self.functions.setTabText(self.functions.indexOf(self.operators), QCoreApplication.translate("MainWindow", u"Operators", None))
        self.addVarPushButton.setText(QCoreApplication.translate("MainWindow", u"Add Variable", None))
        self.deleteVarPushButton.setText(QCoreApplication.translate("MainWindow", u"Delete Variable", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Add List", None))
        self.functions.setTabText(self.functions.indexOf(self.variables), QCoreApplication.translate("MainWindow", u"Variables", None))
        self.createFunctionsPushButton.setText(QCoreApplication.translate("MainWindow", u"Create Functions", None))
        self.deleteFuntionsPushButton.setText(QCoreApplication.translate("MainWindow", u"Delete Functions", None))
        self.functions.setTabText(self.functions.indexOf(self.user_funtions), QCoreApplication.translate("MainWindow", u"User functions", None))
        self.block2textpushButton.setText(QCoreApplication.translate("MainWindow", u"Blocks to text", None))
        self.startpushButton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.stopPushButton.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.program_visual), QCoreApplication.translate("MainWindow", u"LearnBlock", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuTools_robot.setTitle(QCoreApplication.translate("MainWindow", u"&Robot tools", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menuTheme.setTitle(QCoreApplication.translate("MainWindow", u"&Theme", None))
        self.menuProject.setTitle(QCoreApplication.translate("MainWindow", u"&Project", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.menuBlocks.setTitle(QCoreApplication.translate("MainWindow", u"&Blocks", None))
    # retranslateUi

