# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Learnblock.ui',
# licensing of 'Learnblock.ui' applies.
#
# Created: Sun Sep 15 17:02:53 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(955, 790)
        MainWindow.setCursor(QtCore.Qt.ArrowCursor)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.openpushButton.setText("")
        self.openpushButton.setFlat(True)
        self.openpushButton.setObjectName("openpushButton")
        self.horizontalLayout_2.addWidget(self.openpushButton)
        self.savepushButton = QtWidgets.QPushButton(self.centralwidget)
        self.savepushButton.setText("")
        self.savepushButton.setFlat(True)
        self.savepushButton.setObjectName("savepushButton")
        self.horizontalLayout_2.addWidget(self.savepushButton)
        self.zoompushButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoompushButton.setText("")
        self.zoompushButton.setCheckable(True)
        self.zoompushButton.setFlat(True)
        self.zoompushButton.setObjectName("zoompushButton")
        self.horizontalLayout_2.addWidget(self.zoompushButton)
        self.addNumberpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNumberpushButton.setObjectName("addNumberpushButton")
        self.horizontalLayout_2.addWidget(self.addNumberpushButton)
        self.addStringpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addStringpushButton.setObjectName("addStringpushButton")
        self.horizontalLayout_2.addWidget(self.addStringpushButton)
        self.useEventscheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.useEventscheckBox.setObjectName("useEventscheckBox")
        self.horizontalLayout_2.addWidget(self.useEventscheckBox)
        self.clientscomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.clientscomboBox.setCurrentText("EBO")
        self.clientscomboBox.setObjectName("clientscomboBox")
        self.clientscomboBox.addItem("")
        self.clientscomboBox.setItemText(0, "EBO")
        self.horizontalLayout_2.addWidget(self.clientscomboBox)
        self.addClientPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addClientPushButton.setObjectName("addClientPushButton")
        self.horizontalLayout_2.addWidget(self.addClientPushButton)
        self.configRobotPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.configRobotPushButton.setObjectName("configRobotPushButton")
        self.horizontalLayout_2.addWidget(self.configRobotPushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.language = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language.sizePolicy().hasHeightForWidth())
        self.language.setSizePolicy(sizePolicy)
        self.language.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.language.setObjectName("language")
        self.language.addItem("")
        self.language.addItem("")
        self.horizontalLayout_2.addWidget(self.language)
        self.updatepushButton = QtWidgets.QPushButton(self.centralwidget)
        self.updatepushButton.setEnabled(False)
        self.updatepushButton.setObjectName("updatepushButton")
        self.horizontalLayout_2.addWidget(self.updatepushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.Tabwi = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabwi.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tabwi.setFont(font)
        self.Tabwi.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabwi.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tabwi.setObjectName("Tabwi")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_18.addWidget(self.label_4)
        self.pythonCode = QtWidgets.QTextEdit(self.tab)
        self.pythonCode.setObjectName("pythonCode")
        self.verticalLayout_18.addWidget(self.pythonCode)
        self.horizontalLayout_5.addLayout(self.verticalLayout_18)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBoxPythonSize = QtWidgets.QSpinBox(self.tab)
        self.spinBoxPythonSize.setMaximumSize(QtCore.QSize(61, 29))
        self.spinBoxPythonSize.setProperty("value", 12)
        self.spinBoxPythonSize.setObjectName("spinBoxPythonSize")
        self.gridLayout_3.addWidget(self.spinBoxPythonSize, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.startPythonPushButton = QtWidgets.QPushButton(self.tab)
        self.startPythonPushButton.setObjectName("startPythonPushButton")
        self.verticalLayout_19.addWidget(self.startPythonPushButton)
        self.stopPythonPushButton = QtWidgets.QPushButton(self.tab)
        self.stopPythonPushButton.setEnabled(True)
        self.stopPythonPushButton.setObjectName("stopPythonPushButton")
        self.verticalLayout_19.addWidget(self.stopPythonPushButton)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.horizontalLayout_5.addLayout(self.verticalLayout_20)
        self.Tabwi.addTab(self.tab, "")
        self.program_text = QtWidgets.QWidget()
        self.program_text.setEnabled(True)
        self.program_text.setObjectName("program_text")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.program_text)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.program_text)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.textCode = QtWidgets.QTextEdit(self.program_text)
        self.textCode.setObjectName("textCode")
        self.verticalLayout_6.addWidget(self.textCode)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cameraFrame = QtWidgets.QFrame(self.program_text)
        self.cameraFrame.setMinimumSize(QtCore.QSize(320, 240))
        self.cameraFrame.setMaximumSize(QtCore.QSize(320, 240))
        self.cameraFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraFrame.setObjectName("cameraFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cameraFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cameragraphicsView = QtWidgets.QGraphicsView(self.cameraFrame)
        self.cameragraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cameragraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cameragraphicsView.setObjectName("cameragraphicsView")
        self.horizontalLayout_3.addWidget(self.cameragraphicsView)
        self.verticalLayout_5.addWidget(self.cameraFrame)
        self.connectCameraRobotpushButton = QtWidgets.QPushButton(self.program_text)
        self.connectCameraRobotpushButton.setObjectName("connectCameraRobotpushButton")
        self.verticalLayout_5.addWidget(self.connectCameraRobotpushButton)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBoxLeterSize = QtWidgets.QSpinBox(self.program_text)
        self.spinBoxLeterSize.setMaximumSize(QtCore.QSize(61, 29))
        self.spinBoxLeterSize.setProperty("value", 12)
        self.spinBoxLeterSize.setObjectName("spinBoxLeterSize")
        self.gridLayout_2.addWidget(self.spinBoxLeterSize, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.program_text)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.program_text)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.bt2pythonpushButton = QtWidgets.QPushButton(self.program_text)
        self.bt2pythonpushButton.setObjectName("bt2pythonpushButton")
        self.verticalLayout_17.addWidget(self.bt2pythonpushButton)
        self.starttextPushButton = QtWidgets.QPushButton(self.program_text)
        self.starttextPushButton.setObjectName("starttextPushButton")
        self.verticalLayout_17.addWidget(self.starttextPushButton)
        self.stoptextPushButton = QtWidgets.QPushButton(self.program_text)
        self.stoptextPushButton.setEnabled(True)
        self.stoptextPushButton.setObjectName("stoptextPushButton")
        self.verticalLayout_17.addWidget(self.stoptextPushButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_17)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.Tabwi.addTab(self.program_text, "")
        self.program_visual = QtWidgets.QWidget()
        self.program_visual.setObjectName("program_visual")
        self.gridLayout = QtWidgets.QGridLayout(self.program_visual)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.program_visual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(6)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.functions = QtWidgets.QTabWidget(self.splitter)
        self.functions.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functions.sizePolicy().hasHeightForWidth())
        self.functions.setSizePolicy(sizePolicy)
        self.functions.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.functions.setBaseSize(QtCore.QSize(229, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.functions.setFont(font)
        self.functions.setTabPosition(QtWidgets.QTabWidget.West)
        self.functions.setObjectName("functions")
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.search)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.SearchlineEdit = QtWidgets.QLineEdit(self.search)
        self.SearchlineEdit.setObjectName("SearchlineEdit")
        self.verticalLayout_16.addWidget(self.SearchlineEdit)
        self.tableSearch = QtWidgets.QTableWidget(self.search)
        self.tableSearch.setShowGrid(False)
        self.tableSearch.setGridStyle(QtCore.Qt.NoPen)
        self.tableSearch.setObjectName("tableSearch")
        self.tableSearch.setColumnCount(0)
        self.tableSearch.setRowCount(0)
        self.tableSearch.horizontalHeader().setVisible(False)
        self.tableSearch.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tableSearch)
        self.functions.addTab(self.search, "")
        self.control = QtWidgets.QWidget()
        self.control.setObjectName("control")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.control)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.addWhenpushButton = QtWidgets.QPushButton(self.control)
        self.addWhenpushButton.setObjectName("addWhenpushButton")
        self.verticalLayout_12.addWidget(self.addWhenpushButton)
        self.deleteWhenpushButton = QtWidgets.QPushButton(self.control)
        self.deleteWhenpushButton.setEnabled(False)
        self.deleteWhenpushButton.setObjectName("deleteWhenpushButton")
        self.verticalLayout_12.addWidget(self.deleteWhenpushButton)
        self.tableControl = QtWidgets.QTableWidget(self.control)
        self.tableControl.setShowGrid(False)
        self.tableControl.setGridStyle(QtCore.Qt.NoPen)
        self.tableControl.setObjectName("tableControl")
        self.tableControl.setColumnCount(0)
        self.tableControl.setRowCount(0)
        self.verticalLayout_12.addWidget(self.tableControl)
        self.functions.addTab(self.control, "")
        self.operators = QtWidgets.QWidget()
        self.operators.setObjectName("operators")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.operators)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableOperadores = QtWidgets.QTableWidget(self.operators)
        self.tableOperadores.setShowGrid(False)
        self.tableOperadores.setGridStyle(QtCore.Qt.NoPen)
        self.tableOperadores.setObjectName("tableOperadores")
        self.tableOperadores.setColumnCount(0)
        self.tableOperadores.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableOperadores)
        self.functions.addTab(self.operators, "")
        self.variables = QtWidgets.QWidget()
        self.variables.setEnabled(True)
        self.variables.setObjectName("variables")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.variables)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addVarPushButton = QtWidgets.QPushButton(self.variables)
        self.addVarPushButton.setEnabled(True)
        self.addVarPushButton.setObjectName("addVarPushButton")
        self.verticalLayout_2.addWidget(self.addVarPushButton)
        self.deleteVarPushButton = QtWidgets.QPushButton(self.variables)
        self.deleteVarPushButton.setEnabled(False)
        self.deleteVarPushButton.setObjectName("deleteVarPushButton")
        self.verticalLayout_2.addWidget(self.deleteVarPushButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.variables)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tableVariables = QtWidgets.QTableWidget(self.variables)
        self.tableVariables.setShowGrid(False)
        self.tableVariables.setGridStyle(QtCore.Qt.NoPen)
        self.tableVariables.setObjectName("tableVariables")
        self.tableVariables.setColumnCount(0)
        self.tableVariables.setRowCount(0)
        self.verticalLayout.addWidget(self.tableVariables)
        self.functions.addTab(self.variables, "")
        self.user_funtions = QtWidgets.QWidget()
        self.user_funtions.setObjectName("user_funtions")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.user_funtions)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.createFunctionsPushButton = QtWidgets.QPushButton(self.user_funtions)
        self.createFunctionsPushButton.setEnabled(True)
        self.createFunctionsPushButton.setObjectName("createFunctionsPushButton")
        self.verticalLayout_8.addWidget(self.createFunctionsPushButton)
        self.deleteFuntionsPushButton = QtWidgets.QPushButton(self.user_funtions)
        self.deleteFuntionsPushButton.setEnabled(False)
        self.deleteFuntionsPushButton.setObjectName("deleteFuntionsPushButton")
        self.verticalLayout_8.addWidget(self.deleteFuntionsPushButton)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        self.tableUserfunctions = QtWidgets.QTableWidget(self.user_funtions)
        self.tableUserfunctions.setShowGrid(False)
        self.tableUserfunctions.setGridStyle(QtCore.Qt.NoPen)
        self.tableUserfunctions.setObjectName("tableUserfunctions")
        self.tableUserfunctions.setColumnCount(0)
        self.tableUserfunctions.setRowCount(0)
        self.verticalLayout_13.addWidget(self.tableUserfunctions)
        self.functions.addTab(self.user_funtions, "")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.block2textpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.block2textpushButton.setObjectName("block2textpushButton")
        self.horizontalLayout_4.addWidget(self.block2textpushButton)
        self.startpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startpushButton.setObjectName("startpushButton")
        self.horizontalLayout_4.addWidget(self.startpushButton)
        self.stopPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stopPushButton.setMaximumSize(QtCore.QSize(16777215, 27))
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_4.addWidget(self.stopPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.Tabwi.addTab(self.program_visual, "")
        self.verticalLayout_4.addWidget(self.Tabwi)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools_robot = QtWidgets.QMenu(self.menubar)
        self.menuTools_robot.setObjectName("menuTools_robot")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTheme = QtWidgets.QMenu(self.menuEdit)
        self.menuTheme.setObjectName("menuTheme")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuBlocks = QtWidgets.QMenu(self.menubar)
        self.menuBlocks.setObjectName("menuBlocks")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_New_block = QtWidgets.QAction(MainWindow)
        self.actionCreate_New_block.setObjectName("actionCreate_New_block")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionStart_components = QtWidgets.QAction(MainWindow)
        self.actionStart_components.setObjectName("actionStart_components")
        self.actionReboot = QtWidgets.QAction(MainWindow)
        self.actionReboot.setObjectName("actionReboot")
        self.actionShutdown = QtWidgets.QAction(MainWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.actionStart_Simulator = QtWidgets.QAction(MainWindow)
        self.actionStart_Simulator.setObjectName("actionStart_Simulator")
        self.actionNew_project = QtWidgets.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionLoad_Library = QtWidgets.QAction(MainWindow)
        self.actionLoad_Library.setObjectName("actionLoad_Library")
        self.actionDownload_xmls = QtWidgets.QAction(MainWindow)
        self.actionDownload_xmls.setObjectName("actionDownload_xmls")
        self.actionChange_Libraries_path = QtWidgets.QAction(MainWindow)
        self.actionChange_Libraries_path.setObjectName("actionChange_Libraries_path")
        self.actionChange_Workspace = QtWidgets.QAction(MainWindow)
        self.actionChange_Workspace.setObjectName("actionChange_Workspace")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionDownload_examples = QtWidgets.QAction(MainWindow)
        self.actionDownload_examples.setObjectName("actionDownload_examples")
        self.actionDownload_libraries = QtWidgets.QAction(MainWindow)
        self.actionDownload_libraries.setObjectName("actionDownload_libraries")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionBlocks_to_text = QtWidgets.QAction(MainWindow)
        self.actionBlocks_to_text.setObjectName("actionBlocks_to_text")
        self.actionStart_simulated_robot = QtWidgets.QAction(MainWindow)
        self.actionStart_simulated_robot.setObjectName("actionStart_simulated_robot")
        self.actionStart_physical_robot = QtWidgets.QAction(MainWindow)
        self.actionStart_physical_robot.setObjectName("actionStart_physical_robot")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionStop_Simulator = QtWidgets.QAction(MainWindow)
        self.actionStop_Simulator.setObjectName("actionStop_Simulator")
        self.actionStart_aprilTag = QtWidgets.QAction(MainWindow)
        self.actionStart_aprilTag.setObjectName("actionStart_aprilTag")
        self.actionDuplicate = QtWidgets.QAction(MainWindow)
        self.actionDuplicate.setObjectName("actionDuplicate")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionExport_Block = QtWidgets.QAction(MainWindow)
        self.actionExport_Block.setObjectName("actionExport_Block")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAdd_client_robot = QtWidgets.QAction(MainWindow)
        self.actionAdd_client_robot.setObjectName("actionAdd_client_robot")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setCheckable(True)
        self.actionDark.setChecked(False)
        self.actionDark.setObjectName("actionDark")
        self.actionDictionary_Tags = QtWidgets.QAction(MainWindow)
        self.actionDictionary_Tags.setObjectName("actionDictionary_Tags")
        self.actionLoad_Sets_of_Blocks = QtWidgets.QAction(MainWindow)
        self.actionLoad_Sets_of_Blocks.setObjectName("actionLoad_Sets_of_Blocks")
        self.actionSelect_Visible_Blocks = QtWidgets.QAction(MainWindow)
        self.actionSelect_Visible_Blocks.setObjectName("actionSelect_Visible_Blocks")
        self.actionSave_Visible_Blocks = QtWidgets.QAction(MainWindow)
        self.actionSave_Visible_Blocks.setObjectName("actionSave_Visible_Blocks")
        self.actionLoad_Block_Text_Code = QtWidgets.QAction(MainWindow)
        self.actionLoad_Block_Text_Code.setObjectName("actionLoad_Block_Text_Code")
        self.actionSave_Block_Text_Code = QtWidgets.QAction(MainWindow)
        self.actionSave_Block_Text_Code.setObjectName("actionSave_Block_Text_Code")
        self.actionLoad_Python_Code = QtWidgets.QAction(MainWindow)
        self.actionLoad_Python_Code.setObjectName("actionLoad_Python_Code")
        self.actionSave_Python_Code = QtWidgets.QAction(MainWindow)
        self.actionSave_Python_Code.setObjectName("actionSave_Python_Code")
        self.actionAdd_Set_of_Blocks = QtWidgets.QAction(MainWindow)
        self.actionAdd_Set_of_Blocks.setObjectName("actionAdd_Set_of_Blocks")
        self.actionConfigure_Robot = QtWidgets.QAction(MainWindow)
        self.actionConfigure_Robot.setObjectName("actionConfigure_Robot")
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Block_Text_Code)
        self.menuFile.addAction(self.actionSave_Block_Text_Code)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Python_Code)
        self.menuFile.addAction(self.actionSave_Python_Code)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Library)
        self.menuFile.addAction(self.actionChange_Libraries_path)
        self.menuFile.addAction(self.actionChange_Workspace)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools_robot.addAction(self.actionStart_Simulator)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionStart_components)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionReboot)
        self.menuTools_robot.addAction(self.actionShutdown)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionAdd_client_robot)
        self.menuTools_robot.addAction(self.actionConfigure_Robot)
        self.menuTools_robot.addSeparator()
        self.menuTools_robot.addAction(self.actionDownload_xmls)
        self.menuTools_robot.addAction(self.actionDownload_examples)
        self.menuTools_robot.addAction(self.actionDownload_libraries)
        self.menuTheme.addAction(self.actionDark)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuEdit.addAction(self.actionEdit)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionExport_Block)
        self.menuEdit.addAction(self.menuTheme.menuAction())
        self.menuEdit.addAction(self.actionDictionary_Tags)
        self.menuProject.addAction(self.actionBlocks_to_text)
        self.menuProject.addAction(self.actionStart)
        self.menuProject.addAction(self.actionStop)
        self.menuHelp.addAction(self.actionHelp)
        self.menuBlocks.addAction(self.actionCreate_New_block)
        self.menuBlocks.addSeparator()
        self.menuBlocks.addAction(self.actionLoad_Sets_of_Blocks)
        self.menuBlocks.addAction(self.actionAdd_Set_of_Blocks)
        self.menuBlocks.addAction(self.actionSelect_Visible_Blocks)
        self.menuBlocks.addAction(self.actionSave_Visible_Blocks)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuBlocks.menuAction())
        self.menubar.addAction(self.menuTools_robot.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabwi.setCurrentIndex(2)
        self.functions.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.openpushButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.savepushButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.zoompushButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Zoom", None, -1))
        self.addNumberpushButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add Number", None, -1))
        self.addNumberpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add Number", None, -1))
        self.addStringpushButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add String", None, -1))
        self.addStringpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add String", None, -1))
        self.useEventscheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Use Events", None, -1))
        self.addClientPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add Robot", None, -1))
        self.configRobotPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Configure Robot", None, -1))
        self.language.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "ES", None, -1))
        self.language.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "EN", None, -1))
        self.updatepushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Update", None, -1))
        self.Tabwi.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>H</p><p><br/></p></body></html>", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Program", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "px", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Size Leter", None, -1))
        self.startPythonPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.stopPythonPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Python", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Program", None, -1))
        self.connectCameraRobotpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Connect Camera Robot", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "px", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Size Leter", None, -1))
        self.bt2pythonpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Block-Text to Python", None, -1))
        self.starttextPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.stoptextPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.program_text), QtWidgets.QApplication.translate("MainWindow", "Block-Text", None, -1))
        self.functions.setTabText(self.functions.indexOf(self.search), QtWidgets.QApplication.translate("MainWindow", "Search", None, -1))
        self.addWhenpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add When", None, -1))
        self.deleteWhenpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Delete When", None, -1))
        self.functions.setTabText(self.functions.indexOf(self.control), QtWidgets.QApplication.translate("MainWindow", "Control", None, -1))
        self.functions.setTabText(self.functions.indexOf(self.operators), QtWidgets.QApplication.translate("MainWindow", "Operators", None, -1))
        self.addVarPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add Variable", None, -1))
        self.deleteVarPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Variable", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "Add List", None, -1))
        self.functions.setTabText(self.functions.indexOf(self.variables), QtWidgets.QApplication.translate("MainWindow", "Variables", None, -1))
        self.createFunctionsPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Create Functions", None, -1))
        self.deleteFuntionsPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Functions", None, -1))
        self.functions.setTabText(self.functions.indexOf(self.user_funtions), QtWidgets.QApplication.translate("MainWindow", "User functions", None, -1))
        self.block2textpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Blocks to text", None, -1))
        self.startpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.stopPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.Tabwi.setTabText(self.Tabwi.indexOf(self.program_visual), QtWidgets.QApplication.translate("MainWindow", "LearnBlock", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menuTools_robot.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Robot tools", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Edit", None, -1))
        self.menuTheme.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Theme", None, -1))
        self.menuProject.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Project", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Help", None, -1))
        self.menuBlocks.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Blocks", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionCreate_New_block.setText(QtWidgets.QApplication.translate("MainWindow", "Create New Block", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save Project", None, -1))
        self.actionSave.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionOpen_Project.setText(QtWidgets.QApplication.translate("MainWindow", "Open Project", None, -1))
        self.actionOpen_Project.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionSave_As.setText(QtWidgets.QApplication.translate("MainWindow", "Save As", None, -1))
        self.actionSave_As.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, -1))
        self.actionStart_components.setText(QtWidgets.QApplication.translate("MainWindow", "Start EBO Components", None, -1))
        self.actionStart_components.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+1", None, -1))
        self.actionReboot.setText(QtWidgets.QApplication.translate("MainWindow", "Reboot EBO", None, -1))
        self.actionReboot.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+2", None, -1))
        self.actionShutdown.setText(QtWidgets.QApplication.translate("MainWindow", "Shutdown EBO", None, -1))
        self.actionShutdown.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+3", None, -1))
        self.actionStart_Simulator.setText(QtWidgets.QApplication.translate("MainWindow", "Start EBO Simulator", None, -1))
        self.actionStart_Simulator.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+4", None, -1))
        self.actionNew_project.setText(QtWidgets.QApplication.translate("MainWindow", "New Project", None, -1))
        self.actionNew_project.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))
        self.actionLoad_Library.setText(QtWidgets.QApplication.translate("MainWindow", "Load Library", None, -1))
        self.actionLoad_Library.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+L", None, -1))
        self.actionDownload_xmls.setText(QtWidgets.QApplication.translate("MainWindow", "Download xmls", None, -1))
        self.actionDownload_xmls.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+5", None, -1))
        self.actionChange_Libraries_path.setText(QtWidgets.QApplication.translate("MainWindow", "Change Path of Libraries", None, -1))
        self.actionChange_Libraries_path.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Shift+L", None, -1))
        self.actionChange_Workspace.setText(QtWidgets.QApplication.translate("MainWindow", "Change Workspace", None, -1))
        self.actionChange_Workspace.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Shift+W", None, -1))
        self.actionOpen_Recent.setText(QtWidgets.QApplication.translate("MainWindow", "Open Recent", None, -1))
        self.actionDownload_examples.setText(QtWidgets.QApplication.translate("MainWindow", "Download examples", None, -1))
        self.actionDownload_libraries.setText(QtWidgets.QApplication.translate("MainWindow", "Download libraries", None, -1))
        self.actionUndo.setText(QtWidgets.QApplication.translate("MainWindow", "Undo", None, -1))
        self.actionUndo.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Z", None, -1))
        self.actionRedo.setText(QtWidgets.QApplication.translate("MainWindow", "Redo", None, -1))
        self.actionRedo.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, -1))
        self.actionBlocks_to_text.setText(QtWidgets.QApplication.translate("MainWindow", "Blocks to text", None, -1))
        self.actionBlocks_to_text.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F4", None, -1))
        self.actionStart_simulated_robot.setText(QtWidgets.QApplication.translate("MainWindow", "Start (simulated robot)", None, -1))
        self.actionStart_simulated_robot.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F5", None, -1))
        self.actionStart_physical_robot.setText(QtWidgets.QApplication.translate("MainWindow", "Start (physical robot)", None, -1))
        self.actionStart_physical_robot.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F6", None, -1))
        self.actionStop.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.actionStop.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F7", None, -1))
        self.actionStop_Simulator.setText(QtWidgets.QApplication.translate("MainWindow", "Stop Simulator", None, -1))
        self.actionStart_aprilTag.setText(QtWidgets.QApplication.translate("MainWindow", "Start aprilTag", None, -1))
        self.actionDuplicate.setText(QtWidgets.QApplication.translate("MainWindow", "Duplicate", None, -1))
        self.actionDuplicate.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+D", None, -1))
        self.actionEdit.setText(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.actionEdit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))
        self.actionDelete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.actionDelete.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+D", None, -1))
        self.actionExport_Block.setText(QtWidgets.QApplication.translate("MainWindow", "Export Block", None, -1))
        self.actionExport_Block.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+E", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionHelp.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+H", None, -1))
        self.actionAdd_client_robot.setText(QtWidgets.QApplication.translate("MainWindow", "Add Robot Client", None, -1))
        self.actionStart.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.actionDark.setText(QtWidgets.QApplication.translate("MainWindow", "Dark", None, -1))
        self.actionDictionary_Tags.setText(QtWidgets.QApplication.translate("MainWindow", "Dictionary of Tags", None, -1))
        self.actionLoad_Sets_of_Blocks.setText(QtWidgets.QApplication.translate("MainWindow", "Load Sets of Blocks", None, -1))
        self.actionSelect_Visible_Blocks.setText(QtWidgets.QApplication.translate("MainWindow", "Select Visible Blocks", None, -1))
        self.actionSave_Visible_Blocks.setText(QtWidgets.QApplication.translate("MainWindow", "Save Visible Blocks", None, -1))
        self.actionLoad_Block_Text_Code.setText(QtWidgets.QApplication.translate("MainWindow", "Load Block-Text Code", None, -1))
        self.actionSave_Block_Text_Code.setText(QtWidgets.QApplication.translate("MainWindow", "Save Block-Text Code", None, -1))
        self.actionLoad_Python_Code.setText(QtWidgets.QApplication.translate("MainWindow", "Load Python Code", None, -1))
        self.actionSave_Python_Code.setText(QtWidgets.QApplication.translate("MainWindow", "Save Python Code", None, -1))
        self.actionAdd_Set_of_Blocks.setText(QtWidgets.QApplication.translate("MainWindow", "Add Set of Blocks", None, -1))
        self.actionConfigure_Robot.setText(QtWidgets.QApplication.translate("MainWindow", "Configure Robot", None, -1))

